---
title: "Chicago Community Investment Exploration"
output:
    html_document:
    df_print: paged
---

```{r Housekeeping, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}
# Housekeeping (clear workspace, start output file, load packages)
rm(list=ls())
# data cleaning, augmenting, manipulation
library(tidyverse)
library(dplyr)
library(haven)
# library(stargazer)
library(xtable)
library(readxl)
# library(astsa)
library(Hmisc)
library(tidycensus)
library(lubridate)
library(here)

# plotting tools
library(gridExtra)
library(ggplot2)
library(grid)
library(ggrepel)
library(gghighlight)
library(ggalt)
library(scales)
library(extrafont)
# font_import()
# loadfonts()
library(swatches)

# mapping tools
library(raster)
library(rgdal)
library(rgeos)
library(maptools)
library(ggmap)
library(sf)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```


```{r include = FALSE}
monochromatic_C6C3FF <- c(
"#7d77ff",
"#9690ff",
"#aeaaff",
"#c6c3ff",
"#deddff",
"#f6f6ff")
```


```{r include=FALSE}
# dr1iff <- sasxport.get(here("data", "DR1IFF_I.XPT"))
```


```{r include=FALSE}
# ipums_food_sec <- read.delim(here("data", "cps_00001.dat"))
```

```{r include=FALSE}
# ddi <- read_ipums_ddi(here("data", "cps_00001.xml"))
# ipums_food_sec <- read_ipums_micro(ddi)
# View(ipums_food_sec)
```


```{r include=FALSE}
# metadata <- data.frame(attr(ipums_food_sec, "names"), attr(ipums_food_sec, "variable.labels"))
# names(metadata) <- c("var.name", "variable.label")
```

```{r include=FALSE}
# library(SAScii)
# TANF09.instructions <- here("data", "tanf09", "input_TANF09a.sas")
# 
# TANF09.infile.location <- here("data", "tanf09", "TANF09A.TXT")
# 
# #store file as an R data frame
# tanf09 <- 
# 	read.SAScii ( 
# 		TANF09.infile.location, 
# 		TANF09.instructions, 
# 		zipped = F,
# 		lrecl=1210)
```



```{r include=FALSE}
#store file as an R data frame
# tanf.fwf.parameters <-  parse.SAScii(here("data", "tanf09", "input_TANF09c.sas"), beginline = 1)
# tanf09c <- 
# 	read.SAScii ( 
# 		fn= here("data", "tanf09", "TANF09C.TXT"), 
# 		sas_ri=here("data", "tanf09", "input_TANF09c.sas"), 
# 		beginline=3,
# 		zipped = F,
# 		lrecl=721)

```



```{r set_theme}
theme_modest <- function(base_size = 12,
                                  base_family = "Roboto",
                                  base_line_size = base_size / 25,
                                  base_rect_size = base_size / 25) {
  require(grid)
  theme_minimal(base_size = base_size, 
                base_family = base_family,
                base_line_size = base_line_size)  %+replace%
    theme(
        axis.title = element_text(size = rel(0.85)),
        axis.text = element_text(size = rel(0.6)),
        axis.ticks=element_line(colour="grey", size=0.5),
        panel.grid.major = element_line(colour="grey", size=0.4),
        panel.grid.minor = element_line(colour="lightgrey", size=0.25),
        legend.box = NULL, 
        legend.text = element_text(size = rel(0.75)),
        legend.key.height = NULL,
        legend.key.width = NULL,
        legend.key = element_rect(fill = NA, colour = NA),
        legend.background = element_rect(colour = NA, fill=NA), 
        legend.position = "right",
        legend.justification = "center", 
        plot.background = element_rect(colour = NA, fill=NA),
        plot.margin = unit(c(0,0,0,0),"lines"),
        plot.title = element_text(size = rel(1.5), face = "bold", hjust="0.5"),
        plot.subtitle = element_text(size = rel(1.25), face = "bold", hjust="0.5"),
        plot.caption = element_text(size = rel(0.75), hjust = 1),
        strip.background = element_rect(colour = NA, fill=NA),
        strip.text = element_text(face = "bold"),
        panel.spacing = unit(0,"lines"),
        panel.border=element_blank(),
        complete = TRUE
    )
}
  
  

theme_map_modest <- function(base_size = 12) {
  require(grid)
  theme_modest(base_size) %+replace%
    theme(
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text = element_blank(),
        axis.ticks=element_blank(),
        panel.grid.minor.y=element_blank(),
        panel.grid.minor.x=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.border=element_blank(),
        panel.spacing = unit(0,"lines")
        # plot.margin  =  unit(c(0,0,0,0),"lines")
    )
}

theme_set(theme_modest(base_size = 12))
```


```{r import-licenses, message=FALSE, warning=FALSE}
bus_licenses <- read_csv(here::here("data", "Business_Licenses.csv"))
```

```{r view-zip-problems}
problems(bus_licenses)
```


```{r check-zip-integrity}
# investigate nonstandard zip codes
# looks like int'l businesses
bind_cols(bus_licenses[unlist(problems(bus_licenses)[, 'row']), c('LICENSE ID', 'LEGAL NAME', 'DOING BUSINESS AS NAME', 'ADDRESS', 'CITY', 'STATE', 'BUSINESS ACTIVITY')], problems(bus_licenses)[, 'actual']) %>% arrange(ADDRESS) %>% distinct(`DOING BUSINESS AS NAME`, `BUSINESS ACTIVITY`, ADDRESS, CITY, STATE, actual)
```



```{r view-bus-lic}
View(bus_licenses)
```

```{r add-lic-cols}
bus_licenses <- mutate(bus_licenses, 
                       active=ifelse(grepl("AAI",`LICENSE STATUS`),1,0),
                       app_review = difftime(mdy(`LICENSE APPROVED FOR ISSUANCE`,tz="America/Chicago"), mdy(`APPLICATION REQUIREMENTS COMPLETE`,tz="America/Chicago"),unit="days"),
                       license_term = difftime(mdy(`LICENSE TERM EXPIRATION DATE`,tz="America/Chicago"), mdy(`LICENSE TERM START DATE`,tz="America/Chicago"),unit="days"),
                       activity_date = mdy(ifelse(is.na(`LICENSE STATUS CHANGE DATE`), `DATE ISSUED`, `LICENSE STATUS CHANGE DATE`),tz="America/Chicago"),
                       activity_month = lubridate::month(activity_date),
                       activity_yr = lubridate::year(activity_date)
                       )
```


```{r include=FALSE}
wardSides <- read_csv(here::here("data", "wardSides.csv"))
```



```{r}
bus_licenses <- left_join(bus_licenses, wardSides, by="WARD")
```



```{r pre-2015-lic}
# data exploration
bus_licenses %>% group_by(activity_date, WARD) %>% summarise(business_count = n()) %>% 
  filter(activity_date < mdy("1/1/2015"), !is.na(WARD)) %>%
  ggplot() + geom_line(aes(x=activity_date, y=business_count, colour=as.factor(WARD))) +
  gghighlight(min(business_count), max_highlight = 3L) +
  labs(y="Business Count", x="Activity Date", colour="Ward", title="Chicago Ward Business Presence", caption="Data Source: Chicago Open Data Portal") + 
  theme_modest()
```

```{r check-2012-spike}
# look into spike around beginning of 2013
bus_licenses %>% group_by(activity_date, WARD) %>% summarise(bus_count = n()) %>% summarise(max_activity = max(bus_count)) %>% arrange(desc(max_activity))
```

```{r pre-2015-licensing}
# bus_licenses %>% filter(
#   activity_date < mdy("1/1/2015"), !is.na(WARD), !(activity_date== mdy("12/29/2012")), active==1) %>%
#   group_by(activity_date, WARD) %>% summarise(business_count = n()) %>% 
#   ggplot() + geom_line(aes(x=activity_date, y=business_count, colour=as.factor(WARD))) +
#   gghighlight(min(business_count), max_highlight = 3L) +
#   labs(y="Business Count", x="Activity Date", colour="Ward", title="Chicago Ward Business Presence (2002-2015)", caption="Data Source: Chicago Open Data Portal")
```


```{r save-pre-2015-licensing, include=FALSE}
# ggsave("pre_2015_licensing.pdf", width = 30, height = 15, units = "cm")
```


```{r import-former-wards}
wardsPre2015 <- sf::st_read(here::here("data","Geofiles - Chicago Zip Code and Neighborhood", "Boundaries - Wards (2003-2015)","geo_export_fa687596-87b6-4059-afac-b28ce789a674.shp"))
wardsPre2015 <- wardsPre2015 %>% mutate(ctr = sf::st_transform(wardsPre2015, 29101) %>% 
  st_centroid() %>% 
  # this is the crs from wards.2015, which has no EPSG code:
  st_transform(., '+proj=longlat +ellps=WGS84 +no_defs') %>%
  # add as a second geometry col:
  st_geometry())

wardsPre2015 <-wardsPre2015 %>% mutate(lon=map_dbl(geometry, ~st_centroid(.x)[[1]]), # add centroid values for labels
                                    lat=map_dbl(geometry, ~st_centroid(.x)[[2]])) # add centroid values for labels
```


```{r fortify-mapping, message=FALSE}

wards.2015 <- sf::st_read(here::here("data","Geofiles - Chicago Zip Code and Neighborhood","Boundaries - Wards (2015-)","geo_export_0bb2e9fd-20ca-415b-a96a-7722d72c1b41.shp"))
# wards.2015 <- wards.2015 %>% mutate(ctr = sf::st_transform(wards.2015, 29101) %>% 
#   st_centroid() %>% 
#   # this is the crs from wards.2015, which has no EPSG code:
#   st_transform(., '+proj=longlat +ellps=WGS84 +no_defs') %>%
#   # add as a second geometry col:
#   st_geometry())
  
wards.2015 <- wards.2015 %>% mutate(lon=map_dbl(geometry, ~st_centroid(.x)[[1]]), # add centroid values for labels
                                    lat=map_dbl(geometry, ~st_centroid(.x)[[2]])) # add centroid values for labels
```

```{r}
tidycensus::census_api_key(Sys.getenv("CENSUS_API_KEY"))
```


```{r}
# want to know: how population changing/ not changing across tracts - race, age, income, poverty status, safety net takeup
getDemos <- function(acs_year) {
  tidycensus::get_acs(geography = "tract", 
              variables = c(medianIncome = 'B19013_001',
                            perCapitaIncome = 'B19301_001',
                            population = 'B02001_001',
                            belowPovertyPop = 'B17001_002',
                            whitePop = 'B02001_002',
                            blackPop = 'B02001_003',
                            latinxPop = 'B03001_003',
                            asianPop = 'B02001_005',
                            citizenshipPop = 'B05001_001',
                            naturalized = 'B05001_005',
                            noncitizen = 'B05001_006',
                            mobilityPop = 'B07001_001',
                            movedInsideCounty = 'B07001_033',  #hipster age movement inside Cook County
                            movedInside20to24 = 'B07001_021',  #hipster age movement inside Cook County
                            movedInside25to29 = 'B07001_022', 
                            medAgemovedInside = 'B07002_003',
                            renterPop = 'B07013_001',
                            owners = 'B07013_002',
                            renters = 'B07013_003',
                            transportPop = 'B08122_001',
                            publicTransport = 'B08122_013',
                            households = 'B22001_001',
                            householdsSNAP = 'B22001_002',
                            householdsKidsSNAP = 'B22002_003',
                            kidsHealthIns = 'B27001_007',
                            medicarePop = 'C27006_001',
                            maleChildMedicare = 'C27006_004',
                            maleMedicare18_64 = 'C27006_007',
                            maleMedicare65_up = 'C27006_010',
                            femaleMedicare18_64 = 'C27006_017',
                            femaleMedicare65_up = 'C27006_020',
                            femaleChildMedicare = 'C27006_014',
                            medicaidPop = 'C27007_001',
                            maleChildMedicaid = 'C27007_004',
                            maleMedicaid18_64 = 'C27007_007',
                            maleMedicaid65_up = 'C27007_010',
                            femaleMedicaid18_64 = 'C27007_017',
                            femaleMedicaid65_up = 'C27007_020',
                            femaleChildMedicaid = 'C27007_014'
                            ), 
              year = acs_year,
              state = 17, # IL = 17
              county = 031, # Cook County = 031 FIPS
              geometry = TRUE
              # options(tigris_use_cache = TRUE)
              )
}
```


```{r}

demoConversion <- function(acs_year) {
  demo_df <- getDemos(acs_year=acs_year)
  demo_df <- demo_df %>% dplyr::select(-one_of("moe")) %>% spread(variable, estimate)
  demo_df <- demo_df %>% mutate(
                      asian_pct = asianPop/ population,
                      black_pct = blackPop / population,
                      latinx_pct = latinxPop/ population,
                      white_pct = whitePop/ population,
                      other_pct = ifelse((population - blackPop - latinxPop - whitePop - asianPop) / population > 0, 
                                         (population - blackPop - latinxPop - whitePop - asianPop) / population, NA),
                      below_poverty_pct = belowPovertyPop / population,
                      childMedicaid_pct = (femaleChildMedicaid + maleChildMedicaid) / medicarePop,
                      childMedicare_pct = (femaleChildMedicare + maleChildMedicare) / medicarePop,
                      takeupMedicare_pct = (maleChildMedicare + maleMedicare18_64 + maleMedicare65_up +
                          femaleChildMedicare + femaleMedicare18_64 + femaleMedicare65_up) / medicarePop,
                      takeupMedicaid_pct = (maleChildMedicaid + maleMedicaid18_64 + maleMedicaid65_up +
                          femaleChildMedicaid + femaleMedicaid18_64 + femaleMedicaid65_up) / medicaidPop,
                      households_kidsSNAP_pct = householdsKidsSNAP / households,
                      takeupSNAP_pct = householdsSNAP / households,
                      YAmovesInChi_pct = (movedInside20to24 + movedInside25to29) / mobilityPop,
                      movesInChi_pct = movedInsideCounty / mobilityPop,
                      immigrant_pct = (naturalized + noncitizen) / citizenshipPop,
                      renting_pct = renters / renterPop,
                      public_transport_pct = publicTransport / transportPop
                      ) %>% dplyr::select(GEOID, NAME, medianIncome, perCapitaIncome, population, medAgemovedInside, contains("_pct"), geometry)
  
    demo_df <- left_join(demo_df, as.data.frame(demo_df) %>% 
                           dplyr::select(GEOID, NAME, black_pct, latinx_pct, asian_pct, white_pct, other_pct) %>%
                           group_by(GEOID, NAME) %>% 
                           gather(group_name, pct, -GEOID, -NAME) %>% 
                           slice(which.max(pct)) %>% mutate(predominant_race = ifelse(group_name == 'black_pct', 'Black',
                                                       ifelse(group_name == 'white_pct', 'White',
                                                       ifelse(group_name == 'asian_pct', 'Asian',
                                                       ifelse(group_name == 'latinx_pct', 'Latinx',
                                                       ifelse(group_name == 'other_pct', 'Other')))))) %>% 
                           dplyr::select(GEOID, NAME, predominant_race, max_pct = pct), by = "GEOID"
                       )
    return(demo_df)
}
```


```{r}
# test that census calls working
getDemos(2013)
```



```{r}
years <- list(2012, 2013, 2014, 2015, 2016, 2017)

multi_year <-
  map(.x = years, .f=demoConversion) %>%
  map2(.y = years, ~ mutate(.x, id = .y))

all_demos <- reduce(multi_year, rbind)
# rm(multi_year)
```

```{r}
wards.2015.acs.proj <- st_transform(wards.2015, crs = st_crs(all_demos))
all.demos.Chi <- st_intersection(all_demos, wards.2015.acs.proj)
```


```{r facet_wrap_demo_info, message=FALSE, warning=FALSE, fig.width=10}

ggplot(all.demos.Chi %>% filter(!is.na(max_pct))) +
  geom_sf(aes(fill=predominant_race, alpha=max_pct), lwd = 0) +
  scale_alpha(range = c(0.35, 0.9), guide=FALSE) + 
  geom_sf(data = wards.2015.acs.proj, color="black", fill=NA) +
  geom_text_repel(data=filter(wards.2015.acs.proj, ward %in% c(4, 9, 10, 13, 14, 22, 18, 34)), 
                  aes(x=lon, y=lat, label=ward),
                  nudge_x = -.25,
                  direction = "y") +
  coord_sf(datum = NA) +
  theme_map_modest() + 
  # theme(axis.title.y = element_blank(),
  #       axis.title.x = element_blank(),
  #       # axis.text.y = element_blank(),
  #       axis.ticks.x=element_blank(),
  #       panel.grid.minor.y=element_blank(),
  #       panel.grid.minor.x=element_blank(),
  #       # panel.grid.major.y=element_blank(),
  #       panel.grid.major.x=element_blank(),
  #       panel.border=element_blank(),
  #       plot.title = element_text(size = 30, face = "bold", hjust="0.5"),
  #       plot.caption = element_text(size = 15)) +
  facet_wrap( ~ id) + labs(
    title = "Latinx Populations Being Edged out\nof Central, Waterfront Neighborhoods",
    subtitle = "Chicago Racial and Ethnic Group Movement by Census Tract Since 2012",
    caption = "Source: U.S. Census Bureau", fill = "Predominant Race in Tract"
  )
  
```


```{r save-bus-locs, warning=FALSE, include = FALSE}
ggsave("ward_demographics.pdf", width = 30, height = 25, units = "cm")
```


```{r}
bus_licenses <- bus_licenses %>% mutate(activity_wk = lubridate::as_date(cut(activity_date, breaks = "week", start.on.monday = FALSE, origin = lubridate::origin)))
```


```{r fig.width=10}
loop_colors <- c("2" = "#4e96c8",
        "42" = "#b0ddfd",
        "43" = "#62bcfb",
        "44" = "#91d0fc")
bus_licenses %>% filter(activity_date >= "2013-1-1", WARD %in% c(2, 42, 43, 44), active==1) %>% 
    group_by(activity_wk, WARD) %>% summarise(business_count = n()) %>% 
  ggplot() + 
   geom_line(aes(x=ymd(activity_wk), y=business_count, color=as.factor(WARD)), show.legend = FALSE, alpha=0.5) + 
  scale_color_manual(values=loop_colors) +
  geom_label_repel(data = bus_licenses %>% filter(activity_date >= "2013-1-1",
    WARD %in% c(2, 42, 43, 44), active==1) %>% group_by(WARD, activity_wk) %>%
    summarise(business_count = n()) %>% filter(business_count ==
    max(business_count)) %>% slice(which.max(business_count)),
    aes(x=ymd(activity_wk), y=business_count, label=WARD, color=as.factor(WARD)), show.legend = FALSE) +
  theme_modest() +
  scale_x_date(expand=c(0,0))
```


```{r post-2012-lic, warning=FALSE, fig.width=10}

# add column for loop1, loop2, loop3, loop4, pilsen, garfield, 
# then group = ward, color= new var + scale_color_manual
# geom_line(filter(data, ward %in% c(ward1, ward2, ward3, loop4), aes(color=ward)))
# or else, window function on length of license

bus_licenses %>% mutate(bus_licenses, nbrhd_callout = ifelse(WARD == 42, "Ward 42", ifelse(WARD==2, "Ward 2", ifelse(WARD==43), "Ward 43"))
                        )
bus_licenses %>% filter(activity_date >= "2013-1-1", !is.na(WARD), !WARD %in% c(2, 42, 43, 44), active==1) %>%
  group_by(activity_wk, WARD) %>% summarise(business_count = n()) %>% 
  ggplot() +   
  geom_line(aes(x=ymd(activity_wk), y=business_count, colour="grey")) +
  gghighlight(max(business_count), max_highlight = 2, label_key = WARD) + 
   geom_line(filter(data, ward %in% c("loop1", "loop2", "loop3", "loop4", "pilsen", "garfield")),
    aes(x=ymd(activity_wk), y=business_count, color=WARD), show.legend = FALSE, alpha=0.5) + 
  geom_label_repel(data = bus_licenses %>% filter(activity_date >= "2013-1-1",
    WARD %in% c(2, 42, 43, 44), active==1) %>% group_by(WARD, activity_wk) %>%
    summarise(business_count = n()) %>% filter(business_count ==
    max(business_count)) %>% slice(which.max(business_count)),
    aes(x=ymd(activity_wk), y=business_count, label=WARD), color="#62bcfb", show.legend = FALSE) +
  labs(y="Number of Business Licenses", x="Weekly Licenses Issued or Renewed", colour="Chicago Council Ward", caption="Data Source: Chicago Open Data Portal") +
theme_modest() + 
theme(axis.title = element_text(size = 10, face = "bold"), 
      plot.title = element_text(size = 15, face = "bold")) +
 scale_x_date(expand=c(0,0)) +
# scale_y_continuous(limits = c(0,250), expand = c(0, 0)) +
coord_cartesian(ylim=c(0,280), clip = "off") + 
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression(bold("New Business beyond ") *  phantom(bold("Loop Area (Wards 2, 42, 43, 44)")) * phantom(bold(" Concentrated in ")) * phantom(bold("Pilsen (27)")) * phantom(bold(" and ")) * phantom(bold("East Garfield Park (25)")) ), 
        color = "black", size = 7) +   
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression( phantom(bold("New Business beyond ")) * bold("Loop Area (Wards 2, 42, 43, 44)") * phantom(bold(" Concentrated in ")) * phantom(bold("Pilsen (27)")) * phantom(bold(" and ")) * phantom(bold("East Garfield Park (25)")) ), 
        color = "#62bcfb", size = 7) + 
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression( phantom(bold("New Business beyond ")) * phantom(bold("Loop Area (Wards 2, 42, 43, 44)")) * bold(" Concentrated in ") * phantom(bold("Pilsen (27)")) * phantom(bold(" and ")) * phantom(bold("East Garfield Park (25)")) ), 
        color = "black", size = 7) + 
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression( phantom(bold("New Business beyond ")) * phantom(bold("Loop Area (Wards 2, 42, 43, 44)")) * phantom(bold(" Concentrated in ")) * bold("Pilsen (27)") * phantom(bold(" and ")) * phantom(bold("East Garfield Park (25)")) ), 
        color = "#1FBFC3", size = 7) + 
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression( phantom(bold("New Business beyond ")) * phantom(bold("Loop Area (Wards 2, 42, 43, 44)")) * phantom(bold(" Concentrated in ")) * phantom(bold("Pilsen (27)")) * bold(" and ") * phantom(bold("East Garfield Park (25)")) ), 
        color = "black", size = 7) + 
annotate("text", x = ymd("2013-6-1"), y = 275, hjust = 0, parse=TRUE, 
         label=expression( phantom(bold("New Business beyond ")) * phantom(bold("Loop Area (Wards 2, 42, 43, 44)")) * phantom(bold(" Concentrated in ")) * phantom(bold("Pilsen (27)")) * phantom(bold(" and ")) * bold("East Garfield Park (25)") ), 
        color = "#F67770", size = 7) + 
  
annotate("text", x=ymd("2015-7-1"), y=265, label=expression("New Business Entry and Renewal limited to Gentrifying Neighborhoods"), 
         color = "black", size=7, fontface = "bold.italic") 

```



```{r save-post-2012-lic}
ggsave("post2012_licensing.pdf", width = 25, height = 18, units = "cm")
```


```{r avg-monthly-lic, warning=FALSE, fig.width=10}
bus_licenses %>% filter(!is.na(WARD), active==1) %>%
  group_by(activity_month, activity_yr, WARD, SIDE) %>% 
  summarise(business_count = n()) %>% group_by(WARD) %>% arrange(desc(business_count)) %>% 
  ggplot(aes(x=reorder(as.factor(WARD), business_count, FUN = median), y=business_count)) + 
  geom_boxplot(aes(group=as.factor(WARD), fill=as.factor(SIDE)), alpha=0.5) + 
  scale_y_continuous(limits = c(0, 1750)) +
  # scale_x_discrete(breaks=seq(0,50,5)) + 
  # geom_label_repel(aes(group=as.factor(WARD), label=as.factor(WARD))) +
  labs(x="Chicago Council Ward", y="Average Monthly Business Count", caption="Data Source: Chicago Open Data Portal", title="South and West Wards Average Lowest Rate of Business Licensing for 15+ Years", subtitle="Calumet Heights and Westlawn Average less than 25 Business License Issuances per month ",fill="Chicago Area") + 
  theme(axis.title = element_text(size = 10, face = "bold"), 
      plot.title = element_text(size = 15, face = "bold")) +
  theme_modest()
```

```{r save-new-bus, warning=FALSE}
ggsave("avg_ward_business.pdf", width = 25, height = 18, units = "cm")
```


```{r include = FALSE}
school_cols_to_import <- c("RCDTS", "Type",	"School Name", "District",	"City",	"County",	"District Type",	"School Type",	"Grades Served",	"Summative Designation", "Student Enrollment - Total", "Student Enrollment - White %", "Student Enrollment - Black or African American %", "Student Enrollment - Hispanic or Latino %",	"Student Enrollment - Asian %", "Student Enrollment - Low Income %", "Total Number of School Days", "Student Attendance Rate", "Student Chronic Truancy Rate",	"High School Dropout Rate - Total", "High School Dropout Rate - Low Income", "High School 5-Year Graduation Rate - Total", "Avg Class Size - High School", "Avg Class Size – All Grades", "Avg Teaching Exp", "Pupil Teacher Ratio - Elementary", "Pupil Teacher Ratio - High School", "Pupil Certified Staff Ratio", "Pupil Admin Ratio", "Teacher Avg Salary", "Admin Avg Salary", "Teacher Retention Rate", "Principal Turnover within 6 Years",	"Teacher Attendace Rate", "Teacher Evaluation Rate", "Number of Students who took AP classes Grade 9 Total", "Number Low Income of Students who took AP classes Grade 9 Total", "Number of Students who took AP classes Grade 10 Total", "Number Low Income of Students who took AP classes Grade 10 Total", "Number of Students who took AP classes Grade 11 Total", "Number Low Income of Students who took AP classes Grade 11 Total", "Number of Students who took AP classes Grade 12 Total", "Number Low Income of Students who took AP classes Grade 12 Total", "Number of students who took one ore more AP Exams Grade 10", "Number of students who took one ore more AP Exams Grade 11",	"Number of students who took one ore more AP Exams Grade 12")
```


```{r include = FALSE}
# getCensus(name, vintage = NULL, key = Sys.getenv("CENSUS_KEY"), vars,
#   region = NULL, regionin = NULL, time = NULL, date = NULL,
#   period = NULL, monthly = NULL, category_code = NULL,
#   data_type_code = NULL, naics = NULL, pscode = NULL,
#   naics2012 = NULL, naics2007 = NULL, naics2002 = NULL,
#   naics1997 = NULL, sic = NULL)
# https://hrecht.github.io/censusapi/reference/getCensus.html#arguments
```


```{r include=FALSE}
# View(listCensusApis())

# View(listCensusMetadata(name = "acs/acs5", vintage = 2016, type = "geography"))


# sahie_vars <- listCensusMetadata(name = "timeseries/healthins/sahie", 
#     type = "variables")
```

```{r include=FALSE}


# acs_income <- getCensus(name = "acs/acs1",
#     vintage = 2017, 
#     vars = c("NAME", "SAEMHI_PT", "SAEMHI_MOE", "B19013_001MA"), 
#     region = "county:031",
#     regionin = "state:17",
#     time = "from 2009 to 2019")
# head(acs_income)
```


```{r message=FALSE, warning=FALSE}

register_google(key = Sys.getenv("GOOGLEMAPS_KEY"))
```


```{r}

# for (current_year in seq(2009:2019)) {
license_types <- c("ISSUE" = "New Business Licenses", 
                   "RENEW" = "Business License Renewals")  

bl <- bus_licenses %>% filter(activity_yr >= 2009, active == 1, `APPLICATION TYPE`%in% c('ISSUE', 'RENEW')) %>% 
    distinct(`LICENSE ID`, activity_yr, `APPLICATION TYPE`, LONGITUDE, LATITUDE) 
  
  # bounds <- rbind( wards2015.df %>% dplyr::select(long, lat) %>% summarise(long = max(long, na.rm = TRUE),
  #                                                  lat = max(lat, na.rm = TRUE))  ,
  #       wards2015.df %>% dplyr::select(long, lat) %>% summarise(long = min(long, na.rm = TRUE),
  #                                                  lat = min(lat, na.rm = TRUE))
  # )


  
  ggmap(get_googlemap(center = c(lon = -87.732125, lat = 41.83379),
                      zoom = 10, scale = 1,
                      maptype ='terrain',
                      color = 'color',
                      # visible=bounds,
                      key = Sys.getenv("GOOGLEMAPS_KEY"))) + 
    geom_point(data=bl, aes(x=LONGITUDE, y=LATITUDE, color=as.factor(activity_yr)), alpha = 0.05, show.legend = FALSE, na.rm = TRUE) + 
    geom_path(data = wards2015.df, aes(long,lat,group=group), color="black") +
    geom_polygon(data = wards2015.df, aes(long,lat,group=group), fill=NA) + 
    labs(y="Latitude", x="Longitude", colour="Year", title="Money in the Middle", 
         subtitle="Virtually No New Business Entry, Renwal in Chicago Wards 9, 10, 18, or 41 since 2009", 
         caption = "Data Source: City of Chicago Department of Business Affairs and Consumer Protection, Business Licenses"
         ) +
    theme_minimal() + 
    facet_grid(. ~ `APPLICATION TYPE`, labeller=as_labeller(license_types)) +
    theme(
      panel.border = element_blank(),
      axis.text.y = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      axis.text.x = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      plot.title = element_text(size = 15, face = "bold")
    ) +
    scale_x_continuous(limits = c(wards2015.df %>% dplyr::select(long) %>% min() - 0.1, wards2015.df %>% dplyr::select(long) %>% max() + 0.05), expand = c(0, 0)) +
    scale_y_continuous(limits = c(wards2015.df %>% dplyr::select(lat) %>% min() - 0.1, wards2015.df %>% dplyr::select(lat) %>% max()) + 0.05, expand = c(0, 0))
  # }
```



```{r}
ggsave("location_over_googlemap_zoom10.pdf", width = 36, height = 23, units = "cm")
```


```{r include = FALSE}
# reportCard13 <- read_sav(here::here("data", "rc13-spss-data.sav"))
```

```{r include = FALSE}
# reportCard13 <- reportCard13 %>% filter(DistNAME == "City of Chicago SD 299")
# reportCard13 <- reportCard13 %>% mutate(YEAR = "2013")
# report_card_vars <- data.frame(var.name=names(reportCard13), attr(reportCard13,"var.labels"))
```




```{r message=FALSE, warning=FALSE}
voter_turnout15 <- read_csv(here::here("data", "voter_turnout_city_council_2015.csv"), col_names = FALSE, skip=8)
voter_turnout15 <- voter_turnout15 %>% mutate(WARD = ifelse(grepl("WARD", voter_turnout15$X1), as.numeric(gsub("WARD ", "", X1)), NA),
                                              X4 = as.numeric(gsub("%", "", X4)),
                                              YEAR = 2015)
voter_turnout15 <- voter_turnout15 %>% fill(WARD)
```

```{r include=FALSE}
# double-check columns that look empty
voter_turnout15 %>% dplyr::select(X5, X6) %>% distinct()
```

```{r}
voter_turnout15 <- voter_turnout15 %>% dplyr::select(-c(X5, X6))
names(voter_turnout15) <- sapply(c("Precinct","Registered","Ballots","Turnout", "WARD", "YEAR"), toupper)
voter_turnout15 <- voter_turnout15 %>% filter(PRECINCT !="Precinct", !grepl("WARD", PRECINCT), !is.na(PRECINCT))
```


```{r message=FALSE, warning=FALSE}
voter_turnout11 <- read_csv(here::here("data", "voter_turnout_city_council_2011.csv"), col_names = FALSE, skip=8)
voter_turnout11 <- voter_turnout11 %>% mutate(WARD = ifelse(grepl("WARD", voter_turnout11$X1), as.numeric(gsub("WARD ", "", X1)), NA),
                                              X4 = as.numeric(gsub("%", "", X4)),
                                              YEAR=2011)
voter_turnout11 <- voter_turnout11 %>% fill(WARD)
```


```{r}
# double-check columns that look empty
voter_turnout11 %>% dplyr::select(X5, X6) %>% distinct()
```

```{r}
voter_turnout11 <- voter_turnout11 %>% dplyr::select(-c(X5, X6))
names(voter_turnout11) <- sapply(c("Precinct","Registered","Ballots","Turnout", "WARD", "YEAR"), toupper)
voter_turnout11 <- voter_turnout11 %>% filter(PRECINCT !="Precinct", !grepl("WARD", PRECINCT), !is.na(PRECINCT))
```


```{r}
voterTurnout <- bind_rows(voter_turnout11, voter_turnout15)
voterTurnout <- voterTurnout %>% 
  mutate(TURNOUT = round((as.numeric(gsub(",", "", BALLOTS)) / as.numeric(gsub(",", "", REGISTERED))) * 100,1))
rm(voter_turnout11, voter_turnout15)
```


```{r fig.width=8, fig.height=16}

 merge(voterTurnout, wardSides, by="WARD") %>% filter(PRECINCT=="Total") %>% 
  ggplot(aes(x=as.factor(YEAR), y=TURNOUT, group=as.factor(WARD))) + 
    geom_line(size=2, alpha=0.5, color="grey", show.legend = FALSE) +
    # geom_point(aes(color = as.factor(YEAR)),alpha=0.75, size=5, show.legend = FALSE) +
  geom_label(
      # data = merge(voterTurnout, wardSides, by="WARD") %>% filter(PRECINCT=="Total", YEAR == 2011), 
            aes(label = paste0("Ward ", WARD), color = SIDE), 
            label.padding = unit(0.05, "lines"), 
            label.size = 0.0,
            fontface = "bold",
            size = 4) +  
  geom_text_repel(
      data = merge(voterTurnout, wardSides, by="WARD") %>% filter(PRECINCT=="Total", YEAR == 2011),
            aes(label = paste0(TURNOUT, "%")),
            color = "darkgray",
            hjust = "left",
            nudge_x = -.25,
            direction = "y",
            fontface = "bold",
            point.padding	= 3,
            size = 5) +
  geom_text_repel(
    data = merge(voterTurnout, wardSides, by="WARD") %>% filter(PRECINCT=="Total", YEAR == 2015),
            aes(label = paste0(TURNOUT, "%")),
            color = "darkgray",
            hjust = "right",
            nudge_x = .25,
            direction = "y",
            fontface = "bold",
            point.padding	= 3,
            size = 5) +
  scale_x_discrete(position = "top") +
   coord_cartesian(ylim=c(23.5, 60)) +
  theme_minimal() + 
  theme(axis.text.x.top = element_text(size=18, vjust = -10, face="bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          # axis.text.y = element_blank(),
          axis.ticks.x=element_blank(),
          panel.grid.minor.y=element_blank(),
          panel.grid.minor.x=element_blank(),
          # panel.grid.major.y=element_blank(),
          panel.grid.major.x=element_blank(),
          panel.border=element_blank(),
        plot.subtitle = element_text(size = 20, face = "bold.italic", hjust="0.5"),
        plot.title = element_text(size = 30, face = "bold", hjust="0.5"),
        plot.caption = element_text(size = 15)) +   
  labs(title="City-Wide Drop in Voter Turnout Could be Affecting Alderman Motivation \nto Fight Deinvestment", 
         subtitle="Change in Ward Voter Turnout Between Chicago City Council Elections", 
         caption="Source: Chicago Board of Election Commissioners", color="Chicago Area")
         # shape="Election Year", color="Chicago Area") 

```


```{r}
ggsave("ward_election_turnout2011_2015.pdf", width = 36, height = 23, units = "cm")
```





