---
title: "Chicago Community Investment Exploration"
author: Loren Hinkson
output:
    html_document:
      df_print: paged
      code_folding: hide
---

```{r Housekeeping, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}
# Housekeeping (clear workspace, start output file, load packages)
# rm(list=ls())

# data cleaning, augmenting, manipulation
library(tidyverse)
library(dplyr)
library(haven)
# library(stargazer)
library(xtable)
library(readxl)
# library(astsa)
library(Hmisc)
library(tidycensus)
library(lubridate)
library(here)

# plotting tools
library(gridExtra)
library(ggplot2)
library(grid)
library(ggrepel)
library(gghighlight)
library(ggalt)
library(scales)
library(extrafont)
# font_import()
# loadfonts()
library(swatches)

# mapping tools
library(raster)
library(rgdal)
library(rgeos)
library(maptools)
library(tigris)
library(ggmap)
library(sf)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```


```{r include = FALSE}
monochromatic_C6C3FF <- c(
"#7d77ff",
"#9690ff",
"#aeaaff",
"#c6c3ff",
"#deddff",
"#f6f6ff")

diverging_teal <- c(
                    # 'navy' = '#2d3d61',
                    'darkteal' = '#2d4f5a',
                    'forest' = '#2d615f',
                    'plankton' = '#2d706e',
                    'ocean' = '#318791',
                    'mauve' = '#996768',
                    'cocoa' = '#b5725a',
                    'honeymustard' = '#d59349',
                    'goldenrod' = '#edb834',
                    'darkgray' = 'B5B5B5',
                    'palegray' = '#E5E5E5')

```



```{r include=FALSE}
# make it easy to select colors by name, thanks Dr. Simon J!
# Attribution: https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2
get_dt_cols <- function(...) {
  cols <- c(...)
  if (is.null(cols))
    return (diverging_teal)
  diverging_teal[cols]
}
```

```{r include=FALSE}
# set groupings of colors as palettes
dt_palettes <- list(
  `main`  = get_dt_cols("ocean", "mauve", "plankton", "goldenrod"),
  `diverging` = get_dt_cols("darkteal", "honeymustard", "ocean",  "forest", "mauve"),
  `cool`  = get_dt_cols("darkteal", "forest", "plankton", "ocean"),
  `desert`   = get_dt_cols("mauve", "goldenrod", "cocoa", "honeymustard"),
  `mixed` = get_dt_cols("mauve", "goldenrod", "darkteal", "forest", "cocoa", "plankton", "honeymustard"),
  `grey`  = get_dt_cols("palegray", "darkgray")
)
```




```{r include=FALSE}
# function for uilitizing palettes
dt_pal <- function(palette = "main", reverse = FALSE, ...) {
  pal <- dt_palettes[[palette]]
  if (reverse) pal <- rev(pal)
  # pass alpha, other color arguments to colorRampPalette
  colorRampPalette(pal, ...)
}

# function for applying palettes to borders and fills in ggplot2
scale_color_dt <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- dt_pal(palette = palette, reverse = reverse)

  if (discrete) {
    discrete_scale("colour", paste0("dt_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}

scale_fill_dt <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- dt_pal(palette = palette, reverse = reverse)

  if (discrete) {
    discrete_scale("fill", paste0("dt_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}
```



```{r set_theme, message=FALSE, warning=FALSE, include=FALSE}
theme_modest <- function(base_size = 22,
                                  base_family = "Roboto",
                                  base_line_size = base_size / 25,
                                  base_rect_size = base_size / 25) {
  require(grid)
  theme_minimal(base_size = base_size, 
                base_family = base_family,
                base_line_size = base_line_size)  %+replace%
    theme(
        axis.title = element_text(size = rel(1)),
        axis.text = element_text(size = rel(0.75)),
        axis.ticks=element_line(colour="grey", size=0.5),
        panel.grid.major = element_line(colour="grey", size=0.4),
        panel.grid.minor = element_line(colour="lightgrey", size=0.25),
        legend.box = NULL, 
        legend.title = element_text(size = rel(1.25)),
        legend.text = element_text(size = rel(0.75)),
        legend.key.height = NULL,
        legend.key.width = NULL,
        legend.key.size = unit(20, "pt"),
        legend.key = element_rect(fill = NA, colour = NA),
        legend.background = element_rect(colour = NA, fill=NA), 
        legend.position = "right",
        legend.justification = "center", 
        plot.background = element_rect(colour = NA, fill="#DEDEDE"),
        plot.margin = unit(c(0,0,0,0),"lines"),
        plot.title = element_text(size = rel(1.5), face = "bold", hjust="0.5",  margin = margin(t = 15)),
        plot.subtitle = element_text(size = rel(1.25), face = "bold", hjust="0.5",  margin = margin(t = 15)),
        plot.caption = element_text(size = rel(1), hjust = 1),
        strip.background = element_rect(colour = NA, fill=NA),
        strip.text = element_text(face = "bold", size = rel(1.25)),
        panel.spacing = unit(0,"lines"),
        panel.border=element_blank(),
        complete = TRUE
    )
}
  
  

theme_map_modest <- function(base_size = 12) {
  require(grid)
  theme_modest(base_size) %+replace%
    theme(
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text = element_blank(),
        axis.ticks=element_blank(),
        panel.grid.minor.y=element_blank(),
        panel.grid.minor.x=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.border=element_blank(),
        panel.spacing = unit(0,"lines"),
        plot.margin  =  unit(c(2,2,2,2),"lines")
    )
}

theme_set(theme_modest(base_size = 12))
```


```{r import-licenses, message=FALSE, warning=FALSE}
# import business licenses data
# bus_licenses <- read_csv(here::here("data", "Business_Licenses.csv"))
bus_licenses <-  readRDS(here::here("data", "bus_licenses.Rda"))

# view problems report
# problems(bus_licenses)


# investigate nonstandard zip codes flagged -- looks like int'l businesses operating in Chicago
# opting not not to remove
# bind_cols(bus_licenses[unlist(problems(bus_licenses)[, 'row']), c('LICENSE ID', 'LEGAL NAME', 'DOING BUSINESS AS NAME', 'ADDRESS', 'CITY', 'STATE', 'BUSINESS ACTIVITY')], problems(bus_licenses)[, 'actual']) %>% arrange(ADDRESS) %>% distinct(`DOING BUSINESS AS NAME`, `BUSINESS ACTIVITY`, ADDRESS, CITY, STATE, actual)
```


```{r add-lic-cols, include=FALSE}
# add columns for 
# bus_licenses <- mutate(bus_licenses, 
#                        active=ifelse(grepl("AAI",`LICENSE STATUS`),1,0),
#                        app_review = difftime(mdy(`LICENSE APPROVED FOR ISSUANCE`,tz="America/Chicago"), mdy(`APPLICATION REQUIREMENTS COMPLETE`,tz="America/Chicago"),unit="days"),
#                        license_term = difftime(mdy(`LICENSE TERM EXPIRATION DATE`,tz="America/Chicago"), mdy(`LICENSE TERM START DATE`,tz="America/Chicago"),unit="days"),
#                        activity_date = mdy(ifelse(is.na(`LICENSE STATUS CHANGE DATE`), `DATE ISSUED`, `LICENSE STATUS CHANGE DATE`),tz="America/Chicago"),
                      # activity_month = lubridate::as_date(
                      #  cut(activity_date, breaks = "month", start.on.monday = FALSE, origin = lubridate::origin)
                      #  ),
#                        activity_yr = lubridate::year(activity_date)
#                        )
```


```{r include=FALSE}
wardSides <- read_csv(here::here("data", "wardSides.csv"))
```



```{r, include=FALSE}
# bus_licenses <- bus_licenses %>% mutate(activity_wk = lubridate::as_date(cut(activity_date, breaks = "week", start.on.monday = FALSE, origin = lubridate::origin)))
# bus_licenses <- left_join(bus_licenses, wardSides, by="WARD")
# saveRDS(bus_licenses, file = here::here("data", "bus_licenses.Rda"))
```


```{r pre-2015-lic, include=FALSE}
# data exploration
bus_licenses %>% group_by(activity_date, WARD) %>% summarise(business_count = n()) %>% 
  filter(activity_date < mdy("1/1/2015"), !is.na(WARD)) %>%
  ggplot() + geom_line(aes(x=activity_date, y=business_count, colour=as.factor(WARD))) +
  gghighlight(min(business_count), max_highlight = 3L) +
  labs(y="Business Count", x="Activity Date", colour="Ward", 
       title="Chicago Ward Business Presence", 
       caption="Data Source: Chicago Open Data Portal") + 
  theme_modest() + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_color_dt() 
```

```{r check-2012-spike, include=FALSE}
# look into spike around beginning of 2013
# bus_licenses %>% group_by(activity_date, WARD) %>% summarise(bus_count = n()) %>% summarise(max_activity = max(bus_count)) %>% arrange(desc(max_activity))
```

```{r pre-2015-licensing, echo=FALSE, include=FALSE}
# bus_licenses %>% filter(active==1, activity_date < mdy("1/1/2015"), !is.na(WARD), !(activity_date== mdy("12/29/2012"))) %>%
#   group_by(activity_date, WARD) %>% summarise(business_count = n()) %>% 
#   ggplot() + geom_line(aes(x=activity_date, y=business_count, colour=as.factor(WARD))) +
#   gghighlight(min(business_count), max_highlight = 3L) +
#   labs(y="Business Count", x="Activity Date", colour="Ward", 
#        title="Chicago Ward Business Presence (2002-2015)", 
#        caption="Data Source: Chicago Open Data Portal") + 
#   theme_modest() + 
#   theme(panel.grid.major.x = element_blank(),
#         panel.grid.minor = element_blank()) +
#   scale_color_dt() 
```


```{r save-pre-2015-licensing, include=FALSE}
# ggsave("pre_2015_licensing.pdf", width = 30, height = 15, units = "cm")
```




```{r import-former-wards, include=FALSE}
# wardsPre2015 <- sf::st_read(here::here("data","Geofiles - Chicago Zip Code and Neighborhood", "Boundaries - Wards (2003-2015)","geo_export_fa687596-87b6-4059-afac-b28ce789a674.shp"))
# 
# wardsPre2015 <-wardsPre2015 %>% mutate(lon=map_dbl(geometry, ~st_centroid(.x)[[1]]), # add centroid values for labels
#                                     lat=map_dbl(geometry, ~st_centroid(.x)[[2]])) # add centroid values for labels
```




```{r include=FALSE}
# run API key
tidycensus::census_api_key(Sys.getenv("CENSUS_API_KEY"))

# cache census shapefiles
# tigris_cache_dir(here::here("data", "tigris_cache"))
# options(tigris_use_cache = TRUE)
# readRenviron('~/.Renviron')
```


```{r  include=FALSE}
# want to know: how population changing/ not changing across tracts - race, age, income, poverty status, safety net takeup
getDemos <- function(acs_year, geoms=TRUE) {
  tidycensus::get_acs(geography = "tract", 
              variables = c(medianIncome = 'B19013_001',
                            perCapitaIncome = 'B19301_001',
                            population = 'B02001_001',
                            belowPovertyPop = 'B17001_002',
                            whitePop = 'B02001_002',
                            blackPop = 'B02001_003',
                            latinxPop = 'B03001_003',
                            asianPop = 'B02001_005',
                            citizenshipPop = 'B05001_001',
                            naturalized = 'B05001_005',
                            noncitizen = 'B05001_006',
                            mobilityPop = 'B07001_001',
                            movedInsideCounty = 'B07001_033',  #hipster age movement inside Cook County
                            movedInside20to24 = 'B07001_021',  #hipster age movement inside Cook County
                            movedInside25to29 = 'B07001_022', 
                            medAgemovedInside = 'B07002_003',
                            renterPop = 'B07013_001',
                            owners = 'B07013_002',
                            renters = 'B07013_003',
                            transportPop = 'B08122_001',
                            publicTransport = 'B08122_013',
                            households = 'B22001_001',
                            householdsSNAP = 'B22001_002',
                            householdsKidsSNAP = 'B22002_003',
                            kidsHealthIns = 'B27001_007',
                            medicarePop = 'C27006_001',
                            maleChildMedicare = 'C27006_004',
                            maleMedicare18_64 = 'C27006_007',
                            maleMedicare65_up = 'C27006_010',
                            femaleMedicare18_64 = 'C27006_017',
                            femaleMedicare65_up = 'C27006_020',
                            femaleChildMedicare = 'C27006_014',
                            medicaidPop = 'C27007_001',
                            maleChildMedicaid = 'C27007_004',
                            maleMedicaid18_64 = 'C27007_007',
                            maleMedicaid65_up = 'C27007_010',
                            femaleMedicaid18_64 = 'C27007_017',
                            femaleMedicaid65_up = 'C27007_020',
                            femaleChildMedicaid = 'C27007_014'
                            ), 
              year = acs_year,
              state = 17, # IL = 17
              county = 031, # Cook County = 031 FIPS
              geometry = geoms)
}
```


```{r  include=FALSE}

demoConversion <- function(acs_year, geoms = TRUE) {
  demo_df <- getDemos(acs_year=acs_year, geoms)
  demo_df <- demo_df %>% dplyr::select(-one_of("moe")) %>% spread(variable, estimate)
  demo_df <- demo_df %>% mutate(
                      asian_pct = asianPop/ population,
                      black_pct = blackPop / population,
                      latinx_pct = latinxPop/ population,
                      white_pct = whitePop/ population,
                      other_pct = ifelse((population - blackPop - latinxPop - whitePop - asianPop) / population > 0, 
                                         (population - blackPop - latinxPop - whitePop - asianPop) / population, NA),
                      below_poverty_pct = belowPovertyPop / population,
                      childMedicaid_pct = (femaleChildMedicaid + maleChildMedicaid) / medicarePop,
                      childMedicare_pct = (femaleChildMedicare + maleChildMedicare) / medicarePop,
                      takeupMedicare_pct = (maleChildMedicare + maleMedicare18_64 + maleMedicare65_up +
                          femaleChildMedicare + femaleMedicare18_64 + femaleMedicare65_up) / medicarePop,
                      takeupMedicaid_pct = (maleChildMedicaid + maleMedicaid18_64 + maleMedicaid65_up +
                          femaleChildMedicaid + femaleMedicaid18_64 + femaleMedicaid65_up) / medicaidPop,
                      households_kidsSNAP_pct = householdsKidsSNAP / households,
                      takeupSNAP_pct = householdsSNAP / households,
                      YAmovesInChi_pct = (movedInside20to24 + movedInside25to29) / mobilityPop,
                      movesInChi_pct = movedInsideCounty / mobilityPop,
                      immigrant_pct = (naturalized + noncitizen) / citizenshipPop,
                      renting_pct = renters / renterPop,
                      public_transport_pct = publicTransport / transportPop
                      ) %>% 
    dplyr::select(GEOID, NAME, medianIncome, perCapitaIncome, population, medAgemovedInside, contains("_pct"), everything())
  
    demo_df <- left_join(demo_df, as.data.frame(demo_df) %>% 
                           dplyr::select(GEOID, NAME, black_pct, 
                                         latinx_pct, asian_pct, 
                                         white_pct, other_pct) %>%
                           group_by(GEOID, NAME) %>% 
                           gather(group_name, pct, -GEOID, -NAME) %>% 
                           slice(which.max(pct)) %>% 
                           mutate(
                             predominant_race = ifelse(
                             group_name == 'black_pct', 'Black',
                             ifelse(group_name == 'white_pct', 'White',
                             ifelse(group_name == 'asian_pct', 'Asian',
                             ifelse(group_name == 'latinx_pct', 'Latinx',
                             ifelse(group_name == 'other_pct', 'Other')))))) %>% 
                           dplyr::select(GEOID, NAME, predominant_race, max_pct = pct), by = c("GEOID", "NAME")
                       )
    return(demo_df)
}
```


```{r echo=TRUE, include=FALSE}
# test that census calls working
getDemos(2017)
```



```{r message=FALSE,  include=FALSE}
years <- list(2012, 2013, 2014, 2015, 2016, 2017)
multi_year <-
  map(.x = years, .f=demoConversion) %>%
  map2(.y = years, ~ mutate(.x, YEAR = .y))

all_demos <- reduce(multi_year, rbind)
# all_demos_range <- reduce(multi_year, rbind)

# match census sf object to Chicago wards projection
all_demos <-st_transform(all_demos, crs =  st_crs(wards.2015))

saveRDS(all_demos, file = here::here("data", "all_demos_chi_proj.Rda"))
```

```{r  include=FALSE}
# saveRDS(all_demos, file = here::here("data", "all_demos_chi.Rda"))
```




```{r fortify-mapping, message=FALSE, include=FALSE}

# wards.2015 <- sf::st_read(here::here("data","Geofiles - Chicago Zip Code and Neighborhood","Boundaries - Wards (2015-)","geo_export_0bb2e9fd-20ca-415b-a96a-7722d72c1b41.shp"))
```

```{r  include=FALSE}

# 
# all_demos_range <-st_transform(all_demos_range, crs =  st_crs(wards.2015))




# add centroid values for labels
# wards.2015 <- wards.2015  %>% mutate(long=map_dbl(geometry, ~st_centroid(.x)[[1]]), # add centroid values for labels
#                                                       lat=map_dbl(geometry, ~st_centroid(.x)[[2]]))
# wards.2015 <- merge(wards.2015, read_csv(here::here("data", "wardSides.csv")))

# saveRDS(wards.2015, file = here::here("data", "wards2015_sf.Rda"))

# limit Census data to tracts within Chicago ward boundaries
# # all.demos.Chi <- st_intersection(all_demos, wards.2015.acs.proj)

wards_w_demos <- st_join(wards.2015, all_demos_range)
```


In the last decade, underepresented minority populations in Chicago have been increasingly relegated to lower income areas in the South and West of the City. 
```{r facet_wrap_demo_info, message=FALSE, warning=FALSE, fig.width=10, fig.height=15}

# all_demos <-  readRDS(here::here("data", "all_demos_chi.Rda"))
# all_demos.Chi <- readRDS(here::here("data", "all_demos_chi_proj.Rda"))

# wards.2015 <-  readRDS(here::here("data", "wards2015_sf.Rda"))


# plot intersection of Census tracts with chicago wards
ggplot(wards_w_demos) +
  # color based on predominant race based on Census, shaded by percentage of that race
  geom_sf(aes(color=predominant_race, alpha=medianIncome), lwd = 0) +
  scale_color_dt("diverging", na.value=get_dt_cols("palegrey")) +
  scale_alpha(range = c(0.15, 1), guide="none") + 
  
  # outline Chicago wards over data
  geom_sf(data = wards.2015, color="black", fill=NA) +
  
  # label wards with the most movement
  geom_text_repel(data=wards.2015 %>% filter(ward %in% c(10, 18)), 
                  aes(x=long, y=lat, label=ward),
                  fontface="bold",
                  force = 5,
                  size = 6,
                  direction = "both",
                  hjust=0) +
  geom_text_repel(data=wards.2015 %>% filter(ward %in% c(9, 13, 14, 33, 34)), 
                  aes(x=long, y=lat, label=ward),
                  nudge_x = -.35,
                  segment.size = 0.5,
                  segment.color = get_dt_cols("cocoa"),
                  fontface="bold",
                  size = 6,
                  force = 5,
                  direction = "both",
                  hjust=0) +
  geom_text_repel(data = wards.2015 %>% filter(ward %in% c(11)), 
                  aes(x=long, y=lat, label=ward),
                  nudge_x = .15,
                  segment.size = 0.5,
                  segment.color = get_dt_cols("cocoa"),
                  fontface="bold",
                  size = 6,
                  force = 10,
                  direction = "both",
                  hjust = 1) +
  coord_sf(datum = NA) +
  theme_map_modest() + 
  theme(plot.margin = unit(c(20, 0, 0, 0), "pt"),
        plot.title = element_text(face = "bold", hjust="0.5", margin = margin(t = 15)),
        plot.subtitle = element_text( margin = margin(t = 15)),
        plot.caption = element_text(hjust=1)) +
  
  # plot each year separately
  facet_wrap( ~ YEAR) + labs(
    title = "Latinx Populations in Chicago\nPushed to South, West Neighborhoods",
    subtitle = "Chicago Racial and Ethnic Group Movement\nby Census Tract Since 2012 (5 year averages)",
    caption = "Data Source: U.S. Census Bureau", fill = "Predominant Race in Tract")
  

```

```{r}
# all_demos <-  readRDS(here::here("data", "all_demos_chi.Rda"))

# wards_w_all_demos <- st_join(wards.2015, st_transform(all_demos, crs =  st_crs(wards.2015)), largest=TRUE)

wards_w_all_demos %>% filter(YEAR %in% c(2012, 2015, 2017)) %>%
  ggplot() + 
    geom_sf(aes(fill=medianIncome), alpha=0.5) + 
  scale_fill_dt("cool", discrete=FALSE, reverse=TRUE, na.value=get_dt_cols("palegray")) +
  geom_sf(aes(color=predominant_race), fill=NA, lwd=3) +
  scale_color_dt("diverging", discrete=TRUE, na.value=get_dt_cols("palegray"))  +
  theme_map_modest() +
  facet_wrap(~YEAR)
```



```{r save-bus-locs, warning=FALSE, include = FALSE}
ggsave("ward_demographics.pdf", width = 30, height = 25, units = "cm")
```

## Business Activity by Chicago Side Over Time
```{r bus-stagnation, fig.height=12, fig.width=15, message=FALSE, warning=FALSE}
all_wards_all_dates <-  readRDS(here::here("data", "all_wards_all_dates.Rda"))

allDatesCount.df <- all_wards_all_dates %>% expand(SIDE_CLEAN, WARD, `APPLICATION TYPE`, count_date) %>% 
 full_join(all_wards_all_dates) %>%  arrange(SIDE_CLEAN, WARD, `APPLICATION TYPE`, count_date) %>% 
  mutate(
    activity_wk = lubridate::as_date(
      cut(count_date, breaks = "week", start.on.monday = FALSE, origin = lubridate::origin)),
   activity_month = lubridate::as_date(
      cut(count_date, breaks = "month", start.on.monday = FALSE, origin = lubridate::origin)),
   activity_qtr = lubridate::as_date(
      cut(count_date, breaks = "quarter", start.on.monday = FALSE, origin = lubridate::origin)) 
   )

allDatesCount.df %>% filter(`APPLICATION TYPE` %in% c("ISSUE", "RENEW")) %>% group_by(SIDE_CLEAN, activity_qtr) %>% 
  summarise(active_businesses = sum(active_businesses)) %>% 
  # mutate(SIDE_CLEAN <- factor(SIDE_CLEAN, levels=c("Far Southwest","Far Southeast","Northwest","South","Southwest","Central",  "Far North", "North", "West"))) %>%
              ggplot(aes(x=activity_qtr, y=active_businesses, group=forcats::fct_rev(SIDE_CLEAN))) +   
  geom_bar(aes(x=activity_qtr, y=active_businesses, fill=forcats::fct_rev(SIDE_CLEAN)), stat = "identity") +
  scale_fill_dt() +
  geom_text(aes(label=active_businesses), 
            size = 3, position = position_stack(vjust = 0.5), color="white") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%b %y", 
                date_breaks = "1 year", limits = c(ymd("2012-01-01"), ymd("2018-12-31"))) +
  theme_modest() + 
  theme(legend.position = c(0.6, 0.9),
        legend.direction = "horizontal",
        legend.key.size = unit(25, "pt"),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(2,2,2,2),"cm")) +
      labs(y="Number of Business Licenses Issued or Renewed", colour="Chicago Council Ward", caption="Data Source: Chicago Open Data Portal",  title="Business Activity Stagnant in Far Southwest, Far Southeast", subtitle = "Minimal New and Renewing Businesses Since 2012 in Two Chicago Areas", fill="Chicago Area") 
```


## Mapping Chicago's Forgotten Economies
```{r ggmapping, message=FALSE, warning=FALSE, fig.height=17, fig.width=15}
register_google(key = Sys.getenv("GOOGLEMAPS_KEY"))


# read in Chicago ward geos in ggmap-compatible format
wards.shp.2015 <- here::here("data","Geofiles - Chicago Zip Code and Neighborhood","Boundaries - Wards (2015-)","geo_export_0bb2e9fd-20ca-415b-a96a-7722d72c1b41.shp")
wards2015 <- shapefile(wards.shp.2015)
wards2015@data <- mutate(wards2015@data, id = rownames(wards2015@data))
wards2015.points <- fortify(wards2015, region="id")
wards2015.df <- merge(wards2015.points, wards2015@data, by="id")



# name license types
license_types <- c("ISSUE" = "New Business Licenses", 
                   "RENEW" = "Business License Renewals")  

# filter for 2012+ issuances and licenses 
# count each business only once per year)
bl <- bus_licenses %>% filter(activity_yr >= 2012, active == 1, `APPLICATION TYPE`%in% c('ISSUE', 'RENEW')) %>% 
    distinct(`LICENSE ID`, activity_yr, `APPLICATION TYPE`, LONGITUDE, LATITUDE) 
  
# pull in Chicago terrain map from Google Maps
  ggmap::ggmap(ggmap::get_googlemap(center = c(lon = -87.732125, lat = 41.83379),
                      zoom = 10, scale = 1,
                      maptype ='terrain',
                      color = 'color',
                      key = Sys.getenv("GOOGLEMAPS_KEY"))) + 
    
    # layer licenses over each other at extremely low alpha
    geom_point(data=bl, aes(x=LONGITUDE, y=LATITUDE, color=as.factor(activity_yr)), alpha = 0.05, show.legend = FALSE, na.rm = TRUE) + 
    
    # add Chicago Ward boundaries
    geom_path(data = wards2015.df, aes(long,lat,group=group), color="black") +
    geom_polygon(data = wards2015.df, aes(long,lat,group=group), fill=NA) + 
    scale_color_dt() +
    labs(y="Latitude", x="Longitude", colour="Year", title="Money in the Middle", 
         subtitle="Virtually No New Business Entry, Renwal in South, Far Southeast,\nFar Southwest Sides since 2012", 
         caption = "Data Source: City of Chicago Department of Business Affairs and Consumer Protection"
         ) +
    theme_modest() + 
    facet_grid(. ~ `APPLICATION TYPE`, labeller=as_labeller(license_types)) +
    theme(
      panel.border = element_blank(),
      axis.text.y = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      plot.title = element_text(face = "bold", hjust="0.5", margin = margin(t = 15)),
      plot.subtitle = element_text(hjust="0.5", margin = margin(t = 20))
    ) +
    
    # zoom graph to outer ward boundaries
    scale_x_continuous(limits = c(wards2015.df %>% dplyr::select(long) %>% min() - 0.1, wards2015.df %>% dplyr::select(long) %>% max() + 0.05), expand = c(0, 0)) +
    scale_y_continuous(limits = c(wards2015.df %>% dplyr::select(lat) %>% min() - 0.1, wards2015.df %>% dplyr::select(lat) %>% max()) + 0.05, expand = c(0, 0))
```



```{r include=FALSE}
ggsave("location_over_googlemap_zoom10.pdf", width = 36, height = 23, units = "cm")
```




```{r avg-monthly-lic, warning=FALSE, fig.width=15, fig.height=12}
# filter for business license issuances and renewals, and create a monthly count
bus_licenses %>% filter(!is.na(WARD), active==1,  activity_date >= mdy("1/1/2012")) %>%
  group_by(activity_month, activity_yr, WARD, SIDE) %>% 
  summarise(business_count = n()) %>% group_by(WARD, SIDE) %>% arrange(desc(business_count)) %>% 
  
  # plot boxplot of median monthly issuances and renewals for each ward
  ggplot(aes(x=reorder(SIDE, business_count, FUN = median), y=business_count)) + 
  
  # color by Chicago Side
  geom_boxplot(aes(group=as.factor(SIDE), fill=as.factor(SIDE)), show.legend = FALSE) + 
  scale_fill_dt() +
  
  # label each each box by corresponding Ward, just above the median (8 pt)
  geom_text_repel(data = bus_licenses %>% filter(!is.na(WARD), active==1) %>%
                    group_by(activity_month, activity_yr, WARD, SIDE) %>% 
                    summarise(business_count = n()) %>% group_by(SIDE) %>% 
                    arrange(desc(business_count)) %>% 
                    summarise(median_issuances = median(business_count)) %>% 
                    arrange(median_issuances),
                   aes(x=as.factor(SIDE), y = median_issuances + 300, group=as.factor(SIDE),
                       label=as.factor(SIDE), nudge_x = 0.5, direction= "y"),
            color="#6E2C49", fontface="bold", size=5) + 
  
  # limit scale to 750, (one Loop ward's outliers extend ~1000 above other wards)
  # still very clearly the highest even without all outliers visible
  scale_y_continuous(limits = c(0, 750)) +

  labs(x="Chicago Council Ward", y="Average Monthly Business Count", caption="Data Source: Chicago Open Data Portal", title="Least New & Surviving Businesses\nin South, West Wards for 15+ Years", subtitle="Calumet Heights, Westlawn Average less than 25 Monthly\nBusiness License Issuances on Average since 2012",fill="Chicago Area") + 
  theme_modest() +
  theme(
        plot.margin = unit(c(20, 0, 0, 0), "pt"),
        panel.grid.major.x = element_blank(),
        axis.ticks =  element_blank(),
        axis.text.x = element_blank(),
        plot.caption = element_text(hjust=1),
        plot.subtitle = element_text(margin = margin(t = 15))
        )
  
```

```{r save-new-bus, warning=FALSE, include=FALSE}
ggsave("avg_ward_business.pdf", width = 25, height = 18, units = "cm")
```




## Exploring Voter Activation in Deinvested Wards
```{r message=FALSE, warning=FALSE, include=FALSE}
# read in 2015 turnout data and format columns for numeric manipulations, add column for year

# voter_turnout15 <- read_csv(here::here("data", "voter_turnout_city_council_2015.csv"), col_names = FALSE, skip=8)
# voter_turnout15 <- voter_turnout15 %>% mutate(WARD = ifelse(grepl("WARD", voter_turnout15$X1), as.numeric(gsub("WARD ", "", X1)), NA),
#                                               X4 = as.numeric(gsub("%", "", X4)),
#                                               YEAR = 2015)
# voter_turnout15 <- voter_turnout15 %>% fill(WARD)


# double-check columns that look empty
# voter_turnout15 %>% dplyr::select(X5, X6) %>% distinct()


# filter out subtitles and intermediate headings

# voter_turnout15 <- voter_turnout15 %>% dplyr::select(-c(X5, X6))
# names(voter_turnout15) <- sapply(c("Precinct","Registered","Ballots","Turnout", "WARD", "YEAR"), toupper)
# voter_turnout15 <- voter_turnout15 %>% filter(PRECINCT !="Precinct", !grepl("WARD", PRECINCT), !is.na(PRECINCT))


# read in 2011 turnout data and format columns for numeric manipulations, add column for year

# voter_turnout11 <- read_csv(here::here("data", "voter_turnout_city_council_2011.csv"), col_names = FALSE, skip=8)
# voter_turnout11 <- voter_turnout11 %>% mutate(WARD = ifelse(grepl("WARD", voter_turnout11$X1), as.numeric(gsub("WARD ", "", X1)), NA),
#                                               X4 = as.numeric(gsub("%", "", X4)),
#                                               YEAR=2011)
# voter_turnout11 <- voter_turnout11 %>% fill(WARD)


# double-check columns that look empty
# voter_turnout11 %>% dplyr::select(X5, X6) %>% distinct()


# filter out subtitles and intermediate headings

# voter_turnout11 <- voter_turnout11 %>% dplyr::select(-c(X5, X6))
# names(voter_turnout11) <- sapply(c("Precinct","Registered","Ballots","Turnout", "WARD", "YEAR"), toupper)
# voter_turnout11 <- voter_turnout11 %>% filter(PRECINCT !="Precinct", !grepl("WARD", PRECINCT), !is.na(PRECINCT))


# combine 2011 and 2015 data into one dataset

# voterTurnout <- bind_rows(voter_turnout11, voter_turnout15)
# voterTurnout <- voterTurnout %>% 
#   mutate(TURNOUT = round((as.numeric(gsub(",", "", BALLOTS)) / as.numeric(gsub(",", "", REGISTERED))) * 100,1))
# rm(voter_turnout11, voter_turnout15)


# consolidate turnout and change in turnout by Chicago area

# turnoutSides <- merge(voterTurnout, wardSides, by="WARD") %>% filter(PRECINCT=="Total") %>% 
#   group_by(YEAR, SIDE) %>% summarise(MEAN_TURNOUT = round(mean(TURNOUT, na.rm = TRUE), 1)) %>% 
#   spread(YEAR, MEAN_TURNOUT) %>% mutate(DIFFERENCE = `2015` - `2011`) %>% 
#   gather("YEAR", "TURNOUT", -SIDE, -DIFFERENCE) %>% 
#   mutate(DIFFERENCE = ifelse(YEAR==2011, NA, DIFFERENCE)) %>% 
#   dplyr::select(YEAR, everything()) %>% 
#   arrange(SIDE, YEAR)
# 
# saveRDS(turnoutSides, file = here::here("data", "sides_turnout.Rda"))                                  
 

# consolidate turnout and change in turnout by Chicago ward

# turnoutDiff <- voterTurnout %>%filter(PRECINCT=="Total", YEAR %in% c(2011, 2015)) %>% dplyr::select(WARD, TURNOUT, YEAR) %>% 
#   group_by(YEAR, WARD) %>%
#   spread(YEAR, TURNOUT) %>% mutate(DIFFERENCE = `2015` - `2011`) %>% 
#   gather("YEAR", "TURNOUT", -WARD, -DIFFERENCE) %>% 
#   mutate(DIFFERENCE = ifelse(YEAR==2011, NA, DIFFERENCE)) %>% 
#   dplyr::select(YEAR, WARD, TURNOUT, DIFFERENCE) %>% 
#   arrange(YEAR, WARD) %>% group_by(WARD) %>% merge(., wardSides, by="WARD")

# saveRDS(turnoutDiff, file = here::here("data", "wards_turnout.Rda"))
``` 


```{r slopegraph, fig.height=12, fig.width=15}
# read in turnout and change in turnout by Chicago ward and Chciago Side
  turnoutSides <-  readRDS(here::here("data", "sides_turnout.Rda"))
  turnoutDiff <-  readRDS(here::here("data", "wards_turnout.Rda"))

  # plot average turnout in 2011 and 2015 for each Chicago Side
  ggplot(turnoutSides, aes(x=as.factor(YEAR), y=TURNOUT, group=as.factor(SIDE))) + 
  geom_line(aes(colour=SIDE), size=1.5, show.legend = FALSE) +
  # geom_line(data = filter(turnoutSides, (DIFFERENCE > -0)||(is.na(DIFFERENCE))), aes(colour=SIDE), size=1.5, show.legend=FALSE) +
  scale_color_dt() + 
    
  # distribution within each Side.
  geom_line(data = turnoutDiff, aes(group=as.factor(WARD), color=SIDE), size=0.5, alpha=0.35, show.legend = FALSE) +
    
  # add mean turnout (%) for each Side to x-axis
  geom_label(data = turnoutDiff %>% group_by(YEAR, SIDE) %>% summarise(MEAN_TURNOUT = round(mean(TURNOUT, na.rm=TRUE),1)),
            aes(x=as.factor(YEAR), y= MEAN_TURNOUT, label = paste0(MEAN_TURNOUT, "%"), group=as.factor(SIDE)),
            color = "darkgray",
            label.padding = unit(0.05, "lines"),
            label.size = 0.0,
            fontface = "bold",
            size = 4) +

    # label each Side in line graphs for both 2011 and 2015
     geom_label_repel(data = turnoutSides %>% filter(YEAR == 2011),
            aes(label = paste0(SIDE), color = SIDE),
            fill=NA,
            hjust = "left",
            nudge_x = -.25,
            force=5,
            direction = "both",
            fontface = "bold",
            point.padding	= 3,
            size = 5,
            show.legend = FALSE) +
  geom_label_repel(data = turnoutSides %>% filter(YEAR == 2015),
            aes(label = paste0(SIDE), color = SIDE),
            fill=NA,
            hjust = "right",
            nudge_x = .25,
            force = 7.5,
            direction = "both",
            fontface = "bold",
            point.padding	= 3,
            size = 5,
            show.legend = FALSE) +
  # move x-axis text to top of graph
  scale_x_discrete(position = "top") +
   # coord_cartesian(ylim=c(23.5, 60)) +
  theme_modest() + 
  theme(axis.text.x.top = element_text(size=rel(1.25), vjust = -8, face="bold"),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_blank(),
          panel.grid.minor=element_blank(),
          panel.grid.major=element_blank()) +
  labs(title="Highest Voter Turnout In Wards Facing Deinvestment", 
         subtitle="Change in Voter Turnout Between 2011 and 2015 Chicago City Council Elections", 
         caption="Source: Chicago Board of Election Commissioners", color="Chicago Area") +
  annotate("text",  x = 1.25, y = 25, label = "*Underlying ward trends visualized\nbehind Chicago Side trendlines", color= get_dt_cols("mauve"), size=6) 
```


```{r include=FALSE}
ggsave("ward_election_turnout2011_2015.pdf", width = 36, height = 23, units = "cm")
```




```{r eval=FALSE, include=FALSE}
multi_year <-
  map(.x = years, .f=demoConversion, geoms=FALSE) %>%
  map2(.y = years, ~ mutate(.x, YEAR = .y))

just_demos <- reduce(multi_year, rbind) 
# all_demos_range <- reduce(multi_year, rbind)
rm(multi_year)

# saveRDS(just_demos, file = here::here("data", "just_demos.Rda"))
```


```{r message=FALSE}
# read in combined school report card and budget dataset
school_data <-  readRDS(here::here("data", "combined_school_data.Rda"))

# confirm all rows matched to a budget have "Proposed Budget column"
school_data %>% filter(!is.na(School_ID) & is.na(`Proposed Budget`))
  
# add ward to rows from schoolsByWard document parsed above
school_data <- left_join(school_data, 
                         schoolsByWard %>% 
                           dplyr::select(School_ID, 
                                         WARD = Ward, 
                                         NAME_WARD_JOIN = `Unit Name`), 
                         by=c("School_ID" = "School_ID")) %>% 
  dplyr::select(School_ID, WARD, SCHOOL_NAME = `SCHOOL NAME`, NAME_WARD_JOIN, `Proposed Budget`, `SCHOOL TOTAL ENROLLMENT`, everything())

# calculate average spend per student
school_data <- school_data %>% 
  mutate(
    AVG_SPEND_PER_STUDENT = as.numeric( 
    `Proposed Budget`) / as.numeric(gsub(",","",`SCHOOL TOTAL ENROLLMENT`)),
    `SCHOOL TOTAL ENROLLMENT` = as.numeric(gsub(",","",`SCHOOL TOTAL ENROLLMENT`)),
     YEAR = as.numeric(YEAR),
     PREV_YR = as.numeric(YEAR - 1),
     TWO_YR_PRIOR = as.numeric(YEAR - 2) ) %>% 
  dplyr::select(YEAR, PREV_YR, TWO_YR_PRIOR, School_ID, WARD, NAME_WARD_JOIN, 
                CY_BUDGET = `Proposed Budget`, 
                SCHOOL_TOTAL_ENROLLMENT = `SCHOOL TOTAL ENROLLMENT`,
                AVG_SPEND_PER_STUDENT, everything())


front_cols <- c("YEAR", "School_ID", "WARD", "SIDE", "SCHOOL_NAME", "NAME_WARD_JOIN", "CY_BUDGET", "SCHOOL_TOTAL_ENROLLMENT")

school_data <- left_join(school_data, read_csv(here::here("data", "wardSides.csv")),
                         by="WARD") %>% 
  dplyr::select(one_of(front_cols), everything())
```


```{r  fig.height=12, fig.width=15,}
school_data %>% 
  ggplot(group=as.factor(SIDE)) +
  geom_line(aes(x=AVG_SPEND_PER_STUDENT, y=as.factor(YEAR))) +
  geom_point(aes(x=AVG_SPEND_PER_STUDENT, y=as.factor(YEAR), 
                 color=SIDE, size=SCHOOL_TOTAL_ENROLLMENT)) +
  scale_size_continuous(range = c(3,6))
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))) 

```


```{r}
# all_demos <-  readRDS(here::here("data", "all_demos_chi.Rda"))

# wards_w_all_demos <- st_join(wards.2015, st_transform(all_demos, crs =  st_crs(wards.2015)), largest=TRUE)
beg_mid_end_wards_all_demos <- wards_w_all_demos %>% filter(YEAR %in% c(2012, 2015, 2017))
```


```{r  fig.height=12, fig.width=15}

beg_mid_end_wards_all_demos %>% filter(YEAR %in% c(2012, 2015, 2017)) %>%
  ggplot() + 
    geom_sf(aes(fill=medianIncome), alpha=0.5) + 
  scale_fill_dt("cool", discrete=FALSE, reverse=TRUE, na.value=get_dt_cols("palegray")) +
  geom_sf(aes(color=predominant_race), fill=NA, lwd=3) +
  scale_color_dt("diverging", discrete=TRUE, na.value=get_dt_cols("palegray"))  +
  theme_map_modest() +
  facet_wrap(~YEAR)

```



```{r}
school_data %>% group_by(YEAR, SIDE) %>% 
  summarise(median_spend = median(AVG_SPEND_PER_STUDENT)) %>% 
  ggplot(aes(y=median_spend, x=as.numeric(YEAR))) +
  # geom_line(aes(y=AVG_SPEND_PER_STUDENT, x=YEAR)) +
  geom_area(aes(group=as.factor(SIDE), colour=SIDE)) +
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))
        )
```

```{r}
school_data <- school_data %>% 
  mutate(
    ENROLLMENT_RANGE = cut(SCHOOL_TOTAL_ENROLLMENT, 
    breaks=c(0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, Inf),
    labels=c("0-499", "500-999", "1,000-1,499", "1,500-1,999", 
             "2,000-2,499", "2,500-2,999", "3,000-3,499", 
             "3,500-3,999", "4,000-4,499", "4,500-4,999", "5,000+"), 
    ordered_result = TRUE),
        SPEND_RANGE = cut(AVG_SPEND_PER_STUDENT, 
                          breaks=c(0, 2500, 5000, 75000, 10000, 12500, 15000, Inf),
                          labels=c("0-2,499", "2,500-4,999", "5,000-7,499", 
                                   "7,500-9,999", "10,000-12,499", "12,500-14,999",
                                   "15,000+"), 
                          ordered_result = TRUE)) %>%
  dplyr::select(one_of(front_cols), ENROLLMENT_RANGE,SPEND_RANGE, everything())

```



```{r  fig.width=10, message=FALSE, warning=FALSE}
school_data %>% group_by(YEAR, SIDE, WARD, ENROLLMENT_RANGE) %>% summarise(median_spend = median(AVG_SPEND_PER_STUDENT)) %>%
  ggplot(aes(x=median_spend, y=ENROLLMENT_RANGE, group=as.factor(WARD))) +
  geom_point(aes(color=SIDE), position="jitter",size=6) +
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))) +
  facet_wrap(~YEAR)
```

```{r}
left_join(school_data, school_data %>% filter(!is.na(SCHOOL_ID)) %>% 
            dplyr::select(YEAR, SCHOOL_ID, PRIOR)
```



