---
title: "Chicago Public Schools Data Import"
output: html_notebook
---


```{r include = FALSE}
# pipe shortcut: *Cmd+Shift+M* 
```



```{r Housekeeping, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}
# Housekeeping (clear workspace, start output file, load packages)
# rm(list=ls())
library(Hmisc)
library(haven)
library(readxl)
library(lubridate)
library(tidyverse)
library(here)
```


```{r include=FALSE}
# Experiment with one file to write functions
# rc17Layout <- mutate(rc17Layout, descriptions = ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3)))
```

```{r include=FALSE}
# rc17Layout <- read_excel(here::here("data","RC17_layout.xlsx"), sheet="RC17", col_names=FALSE)
```

```{r include=FALSE}
# rc17Layout %>% filter(is.na(as.numeric(X__1)))
```

```{r warning=FALSE, include=FALSE}
# rc17Layout <- rc17Layout %>% filter(!is.na(as.numeric(X__1)))
```

```{r include=FALSE}
# rc17Layout %>% filter(!is.na(X__2))
```

```{r include=FALSE}
# rc17Layout <- rc17Layout %>% select(-one_of(c("X__2")))
```

```{r include=FALSE}
# rc17Layout <- mutate(rc17Layout, descriptions = ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3)))
```


```{r}
importReportCards <- function(file, year, layout) {
   repCard <- read.delim(here::here("data", file), header = FALSE, sep=";")
   print(paste("layout length: ", nrow(layout)))
   print(paste("report card columns: ", ncol(repCard)))
   
   if (colnames(repCard) == nrow(layout)) {
      names(repCard) = layout %>% select(X__6)
   } else if (ncol(repCard) > nrow(layout)) {
      name_vec = layout$descriptions
      names(repCard) <-  append(name_vec, sprintf("V%1d", 1:(ncol(repCard) - nrow(layout))))
   }
   
   cols = colnames(repCard)
   if ("DistNAME" %in% cols) {
      repCard <-  repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else if ("District" %in% cols) {
       repCard <-  repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else if ("DISTRICT NAME" %in% cols) {
       repCard <- repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else {
     print("Error: Check District column name")
   }

   id_info = c("SCHOOL ID (R-C-D-T-S)", "SCHOOL TYPE CODE (0,1,2,C)", "SCHOOL NAME", "DISTRICT NAME", "CITY", "COUNTY")
   repCard <- repCard %>% select(id_info, contains("SCHOOL"))
   repCard <-  mutate(repCard, YEAR = year)
   return(repCard)
   } 
```



```{r}
processLayout <- function(file, sheet, colnames) {
  layout = read_excel(here::here("data", file), sheet=sheet, col_names=colnames)
  layout = layout %>% filter(!is.na(as.numeric(X__1)))
  layout = layout %>% dplyr::select(-one_of(c("X__2")))
  layout = mutate(layout, descriptions = toupper(ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3))))
  return(layout)
}
```



```{r}
rc_key_phrases <- c("Summative Designation", "Low-Income", "Enrollment", "School Days", "Attendance Rate", "Truancy",	"Truant", "Truants", "Dropout", 'Dropout Rate', "DROPOUT RATE SCHOOL %", "Graduation Rate", "Grad Rate", "Class Size", "Teaching Exp", "Teacher Exp", "Teaching Exp.", "Teacher Exp.", "Teaching Experience", "Provisional Credentials", "Teacher Ratio", "Admin Ratio", "Pupil-Teacher", "Pupil-Admin", "Teacher Avg Salary", "Admin Avg Salary", "Teacher Retention", "Principal Turnover",	"Teacher Attendace", "Teacher Evaluation", "AP Classes", "AP Exams")
rc_key_phrases <- sapply(rc_key_phrases, toupper)
```


```{r}
id_info <- c("YEAR", "SCHOOL ID (R-C-D-T-S)", "SCHOOL NAME", "DISTRICT NAME", "CITY", "COUNTY", "SCHOOL TYPE NAME", "GRADES IN SCHOOL", "SCHOOL - WHITE %", "SCHOOL - BLACK %", "SCHOOL - HISPANIC %", "SCHOOL - ASIAN %", "LOW-INCOME SCHOOL %")
```


```{r include=FALSE}
# data exploration 
rc15Layout <- processLayout(file="RC15-layout.xlsx", sheet="RC15", colnames=FALSE)
```

```{r include=FALSE}
rc15 <- importReportCards("rc15.txt", "2015", rc15Layout)
```

```{r}
rc15 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```

```{r}
rc16Layout <- processLayout(file="RC16-layout.xlsx", sheet="RC16", colnames=FALSE)
```

```{r}
rc16 <- importReportCards("rc16.txt", "2016", rc16Layout)
```

```{r}
rc16 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
rc17Layout <- processLayout(file="RC17_layout.xlsx", sheet="RC17", colnames=FALSE)
```

```{r}
rc17 <- importReportCards("rc17.txt", "2017", rc16Layout)
```

```{r}
rc17 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
rc15 <- rc15 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
rc16 <- rc16 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
rc17 <- rc17 %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
ncol(rc15)
ncol(rc16)
ncol(rc17)
```


```{r}
full_term <- plyr::rbind.fill(rc15, rc16, rc17)
```

```{r}
rc18 <- read_xlsx(here::here("data", "Report-Card-Public-Data-Set.xlsx"), sheet = "General")
rc18 <- mutate(rc18, YEAR="2018")
colnames(rc18) <- sapply(colnames(rc18), toupper)
```

```{r}
rc18 <- rc18 %>% rename(
  "SCHOOL ID (R-C-D-T-S)" = "RCDTS",
  "SCHOOL TYPE NAME" = "SCHOOL TYPE",
  "GRADES IN SCHOOL" = "GRADES SERVED",
  "DISTRICT NAME" = "DISTRICT",
  "SCHOOL - WHITE %" = "STUDENT ENROLLMENT - WHITE %", 
  "SCHOOL - BLACK %" = "STUDENT ENROLLMENT - BLACK OR AFRICAN AMERICAN %",
  "SCHOOL - HISPANIC %" = "STUDENT ENROLLMENT - HISPANIC OR LATINO %",
  "SCHOOL - ASIAN %" = "STUDENT ENROLLMENT - ASIAN %",
  "SCHOOL TOTAL ENROLLMENT"  = "STUDENT ENROLLMENT - TOTAL",
  "LOW-INCOME SCHOOL %" = "STUDENT ENROLLMENT - LOW INCOME %",
  "TOTAL SCHOOL DAYS - SCHOOL" = "TOTAL NUMBER OF SCHOOL DAYS",
  "ATTENDANCE RATE SCHOOL %  -  ALL" = "STUDENT ATTENDANCE RATE",
  "ATTENDANCE RATE SCHOOL %  -  MALE" = "STUDENT ATTENDANCE RATE - MALE",
  "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "STUDENT ATTENDANCE RATE - FEMALE",
  "ATTENDANCE RATE SCHOOL %  -  WHITE" = "STUDENT ATTENDANCE RATE - WHITE",
  "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "STUDENT ATTENDANCE RATE - HISPANIC OR LATINO",
  "CHRONIC TRUANTS RATE SCHOOL %" = "STUDENT CHRONIC TRUANCY RATE",
  "ATTENDANCE RATE SCHOOL %  -  BLACK" = "STUDENT ATTENDANCE RATE - BLACK OR AFRICAN AMERICAN",
  "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "STUDENT ATTENDANCE RATE - ASIAN",
  "CHRONIC TRUANTS # - SCHOOL" = "CHRONICALLY TRUANT STUDENTS",
  "DROPOUT RATE  SCHOOL %" = "HIGH SCHOOL DROPOUT RATE - TOTAL",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - TOTAL",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - MALE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - FEMALE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - WHITE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - ASIAN",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - LOW INCOME",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - TOTAL",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - MALE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - FEMALE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - WHITE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - ASIAN",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - LOW INCOME",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - TOTAL",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - MALE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - FEMALE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - WHITE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - ASIAN",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  LOW INCOME"  = "HIGH SCHOOL 6-YEAR GRADUATION RATE - LOW INCOME",
  "AVG CLASS SIZE - SCHOOL (KG)" = "AVG CLASS SIZE - KINDERGARTEN",
  "AVG CLASS SIZE - SCHOOL (GR1)" = "AVG CLASS SIZE - 1",
  "AVG CLASS SIZE - SCHOOL (GR2)" = "AVG CLASS SIZE - 2",
  "AVG CLASS SIZE - SCHOOL (GR3)" = "AVG CLASS SIZE - 3",
  "AVG CLASS SIZE - SCHOOL (GR4)" = "AVG CLASS SIZE - 4",
  "AVG CLASS SIZE - SCHOOL (GR5)" = "AVG CLASS SIZE - 5",
  "AVG CLASS SIZE - SCHOOL (GR6)" = "AVG CLASS SIZE - 6",
  "AVG CLASS SIZE - SCHOOL (GR7)" = "AVG CLASS SIZE - 7",
  "AVG CLASS SIZE - SCHOOL (GR8)" = "AVG CLASS SIZE - 8",
  "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVG CLASS SIZE - HIGH SCHOOL",
  "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "AVG CLASS SIZE – ALL GRADES",
  "TEACHER RETENTION RATE (SCHOOL)" = "TEACHER RETENTION RATE",
  "# OF PRINCIPAL TURNOVER WITHIN 6 YEARS (SCHOOL)"  = "PRINCIPAL TURNOVER WITHIN 6 YEARS",
  "TEACHER ATTENDANCE RATE (SCHOOL)  -  ALL" = "TEACHER ATTENDACE RATE",
  "# OF CTE ENROLLMENT (SCHOOL)" = "# OF CTE ENROLLMENT",
  "# OF AP EXAMS TAKEN BY GRADE 10 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 10",
  "# OF AP EXAMS PASSED BY GRADE 10 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 10",
  "# OF GRADE 10 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 10",
  "# OF AP EXAMS TAKEN BY GRADE 11 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 11",
  "# OF AP EXAMS PASSED BY GRADE 11 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 11",
  "# OF GRADE 11 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 11",
  "# OF GRADE 11 STUDENTS PASSED ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO PASSED ONE ORE MORE AP EXAMS GRADE 11",
  "# OF AP EXAMS TAKEN BY GRADE 12 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 12",
  "# OF AP EXAMS PASSED BY GRADE 12 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 12",
  "# OF GRADE 12 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 12",
  "# OF GRADE 12 STUDENTS PASSED ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO PASSED ONE ORE MORE AP EXAMS GRADE 12"
  )

rc18 %>% filter(grepl("City of Chicago", `DISTRICT NAME`)) %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")), -contains("IEP"), -contains("TWO OR MORE"), -contains("OTHER"), -contains("ALASKA"), -contains("NUMBER EL"), -contains(" - SUBREGION"), -contains(" - DISTRICT"))
```

```{r}
rc18 <- rc18 %>% filter(grepl("City of Chicago", `DISTRICT NAME`)) %>% select(id_info, matches(paste(rc_key_phrases,collapse="|")), -contains("IEP"), -contains("TWO OR MORE"), -contains("OTHER"), -contains("ALASKA"), -contains("NUMBER EL"), -contains(" - SUBREGION"), -contains(" - DISTRICT"))
```

```{r}
# check for column name changes from previous years
setdiff(colnames(full_term), colnames(rc18))
```

```{r}
# check for newly introduced columns in 2018
setdiff(colnames(rc18), colnames(full_term))
```


```{r}
full_term <- plyr::rbind.fill(full_term, rc18)
```


```{r include=FALSE}
# attempt at fuzzzy matching between 2018 and previous years
# col_check <- data.frame(name2018=colnames(rc18),
#                  prevname=NA*length(colnames(rc18)), 
#                  stringsAsFactors=FALSE) 
# for(i in 1:length(col_check$name2018) ) {
#    x <- agrep(pattern=col_check$name2018[i], x=colnames(rc_2015_to_2018),
#    ignore.case=TRUE, value=TRUE,
#    max.distance = 0.01, useBytes = TRUE)
#    x <- paste0(x,"")
#    col_check$prevname[i] <- x
# }
# View(col_check)
```

```{r}
rc13 <- haven::read_sas(here::here("data", "rc13-sas-data", "rc13-sas-data.sas7bdat"))
rc14 <- haven::read_sas(here::here("data", "rc14-sas-data", "rc14-sas-data.sas7bdat"))
```

```{r}
# dim(rc13 %>% filter(grepl("City of Chicago", DistNAME)))
# dim(rc14 %>% filter(grepl("City of Chicago", DistNAME)))
```
```{r}
rc13 <- rc13 %>% filter(grepl("City of Chicago", DistNAME))
rc14 <- rc14 %>% filter(grepl("City of Chicago", DistNAME))
rc13 <- mutate(rc13, YEAR = "2013")
rc14 <- mutate(rc13, YEAR = "2014")
```


```{r}

rc13 <- rc13 %>% rename("SCHOOL ID (R-C-D-T-S)" = "SchRcdts",
                "SCHOOL TYPE NAME" = "SchTYPENAME",
                "GRADES IN SCHOOL" = "GRSINSch",
                "SCHOOL NAME" = "SchNAME",
                "DISTRICT NAME" = "DistNAME",
                "SCHOOL - WHITE %" = "SchWhPct", 
                "SCHOOL - BLACK %" = "SchBlPct",
                "SCHOOL - HISPANIC %" = "SchHispPct",
                "SCHOOL - ASIAN %" = "SchAsiPct",
                "SCHOOL TOTAL ENROLLMENT"  = "SchTotEnroll",
                "LOW-INCOME SCHOOL %" = "LowIncSchPct",
                "TOTAL SCHOOL DAYS - SCHOOL" = "TotSchDAYSSch",
                "ATTENDANCE RATE SCHOOL %  -  ALL" = "AttendRATESchPctALL",
                "ATTENDANCE RATE SCHOOL %  -  MALE" = "AttendRATESchPctMALE",
                "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "AttendRATESchPctFem",
                "ATTENDANCE RATE SCHOOL %  -  WHITE" = "AttendRATESchPctWh",
                "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "AttendRATESchPctHisp",
                "ATTENDANCE RATE SCHOOL %  -  BLACK" = "AttendRATESchPctBl",
                "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "AttendRATESchPctAsi",
                "CHRONIC TRUANTS # - SCHOOL" = "CHRONICTRUANTSNumSch",
                "CHRONIC TRUANTS RATE SCHOOL %" = "CHRONICTRUANTSRATESchPct",
                "DROPOUT RATE  SCHOOL %" = "DROPOUTRATESchPct",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS5YrGRADRATESchPctALL",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS4YrGRADRATESchPctALL",
                "AVG CLASS SIZE - SCHOOL (KG)" = "AVGCLASSSIZESchKG",
                "AVG CLASS SIZE - SCHOOL (GR1)" = "AVGCLASSSIZESchGR1",
                "AVG CLASS SIZE - SCHOOL (GR2)" = "AVGCLASSSIZESchGR2",
                "AVG CLASS SIZE - SCHOOL (GR3)" = "AVGCLASSSIZESchGR3",
                "AVG CLASS SIZE - SCHOOL (GR4)" = "AVGCLASSSIZESchGR4",
                "AVG CLASS SIZE - SCHOOL (GR5)" = "AVGCLASSSIZESchGR5",
                "AVG CLASS SIZE - SCHOOL (GR6)" = "AVGCLASSSIZESchGR6",
                "AVG CLASS SIZE - SCHOOL (GR7)" = "AVGCLASSSIZESchGR7",
                "AVG CLASS SIZE - SCHOOL (GR8)" = "AVGCLASSSIZESchGR8",
                "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVGCLASSSIZESchHS",
                "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "OVERALLAvgCLASSSIZESch",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS4YrGRADRATESchPctMALE",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS4YrGRADRATESchPctFem",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS4YrGRADRATESchPctWh",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS4YrGRADRATESchPctBl",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS4YrGRADRATESchPctHisp",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS4YrGRADRATESchPctAsi",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS4YrGRADRATESchPctLowInc",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS5YrGRADRATESchPctMALE",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS5YrGRADRATESchPctFem",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS5YrGRADRATESchPctWh",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS5YrGRADRATESchPctBl",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS5YrGRADRATESchPctHisp",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS5YrGRADRATESchPctAsi",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS5YrGRADRATESchPctLowInc")

rc14 <- rc14 %>%  rename("SCHOOL ID (R-C-D-T-S)" = "SchRcdts",
                "SCHOOL TYPE NAME" = "SchTYPENAME",
                "GRADES IN SCHOOL" = "GRSINSch",
                "SCHOOL NAME" = "SchNAME",
                "DISTRICT NAME" = "DistNAME",
                "SCHOOL - WHITE %" = "SchWhPct", 
                "SCHOOL - BLACK %" = "SchBlPct",
                "SCHOOL - HISPANIC %" = "SchHispPct",
                "SCHOOL - ASIAN %" = "SchAsiPct",
                "SCHOOL TOTAL ENROLLMENT"  = "SchTotEnroll",
                "LOW-INCOME SCHOOL %" = "LowIncSchPct",
                "TOTAL SCHOOL DAYS - SCHOOL" = "TotSchDAYSSch",
                "ATTENDANCE RATE SCHOOL %  -  ALL" = "AttendRATESchPctALL",
                "ATTENDANCE RATE SCHOOL %  -  MALE" = "AttendRATESchPctMALE",
                "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "AttendRATESchPctFem",
                "ATTENDANCE RATE SCHOOL %  -  WHITE" = "AttendRATESchPctWh",
                "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "AttendRATESchPctHisp",
                "ATTENDANCE RATE SCHOOL %  -  BLACK" = "AttendRATESchPctBl",
                "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "AttendRATESchPctAsi",
                "CHRONIC TRUANTS # - SCHOOL" = "CHRONICTRUANTSNumSch",
                "CHRONIC TRUANTS RATE SCHOOL %" = "CHRONICTRUANTSRATESchPct",
                "DROPOUT RATE  SCHOOL %" = "DROPOUTRATESchPct",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS5YrGRADRATESchPctALL",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS4YrGRADRATESchPctALL",
                "AVG CLASS SIZE - SCHOOL (KG)" = "AVGCLASSSIZESchKG",
                "AVG CLASS SIZE - SCHOOL (GR1)" = "AVGCLASSSIZESchGR1",
                "AVG CLASS SIZE - SCHOOL (GR2)" = "AVGCLASSSIZESchGR2",
                "AVG CLASS SIZE - SCHOOL (GR3)" = "AVGCLASSSIZESchGR3",
                "AVG CLASS SIZE - SCHOOL (GR4)" = "AVGCLASSSIZESchGR4",
                "AVG CLASS SIZE - SCHOOL (GR5)" = "AVGCLASSSIZESchGR5",
                "AVG CLASS SIZE - SCHOOL (GR6)" = "AVGCLASSSIZESchGR6",
                "AVG CLASS SIZE - SCHOOL (GR7)" = "AVGCLASSSIZESchGR7",
                "AVG CLASS SIZE - SCHOOL (GR8)" = "AVGCLASSSIZESchGR8",
                "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVGCLASSSIZESchHS",
                "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "OVERALLAvgCLASSSIZESch",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS4YrGRADRATESchPctMALE",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS4YrGRADRATESchPctFem",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS4YrGRADRATESchPctWh",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS4YrGRADRATESchPctBl",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS4YrGRADRATESchPctHisp",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS4YrGRADRATESchPctAsi",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS4YrGRADRATESchPctLowInc",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS5YrGRADRATESchPctMALE",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS5YrGRADRATESchPctFem",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS5YrGRADRATESchPctWh",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS5YrGRADRATESchPctBl",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS5YrGRADRATESchPctHisp",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS5YrGRADRATESchPctAsi",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS5YrGRADRATESchPctLowInc")


```




```{r}
setdiff(sapply(colnames(rc13), toupper), sapply(colnames(rc14), toupper))
```


```{r}
# double-check "COMING SOON" columns are all NA in 2013 data
rc13 %>% select(contains("Coming")) %>% summarise_all(funs(n_distinct(.)))
```


```{r}
# double-check "COMING SOON" columns are all NA in 2014 data
rc14 %>% select(contains("Comming")) %>% summarise_all(funs(n_distinct(.)))
```


```{r}
# remove columns with non-pertinent info
rc13 <- rc13 %>%  select(-contains("Coming"), -contains("PctOFStudsNOTTAKING"), -contains("Nhopi"), -contains("TomR"), -contains("StaPct"), -contains("DistPct"), -contains("EnrollFORGR"), -contains("DistGR"), -contains("DistEnroll"),-contains("NumSta"), -contains("StaEnroll"), -contains("Subr"), -contains("MINPERDAY"), -contains("DistDOLLAR"), -contains("EnrollIN"), -contains("ISAT"), -contains("DistBELOW"), -contains("DistMeet"), -contains("Distexceed"), -contains("DistAcadWarn"), -contains("StaBELOW"), -contains("StaMeet"), -contains("Staexceed"), -contains("StaAcadWarn"),  -contains("SCORE"), -contains("SchAcadWarn"), -contains("SchBELOW"), -contains("SchMeet"), -contains("Schexceed"), -contains("PROGRESSING"), -contains("ATTEMPTING"),-contains("FORMeetAND"), -contains("ATTAINING"), -contains("EMERGING"), -contains("PROFICIENT"), -contains("BASIC"), -contains("ADVANCED"), -contains("ParticipatRATE"), -contains("MAKINGAYP"), -contains("Readtest"), -contains("TAKINGMATHTESTS"), -contains("OTHERINDICATO"), -contains("IMPROVEMENT"), -contains("DOLLAR"), -contains("EXPEND"), -contains("SchSINTHESta"), -contains("DistSINTHESta"), -contains("SchSINTHEDist"), -contains("PctMult"), -contains("PctNhopi"), -contains("PctNat"), -contains("ACTCOMP"), -contains("LEGISLATIVE"), -contains("IEP"), -contains("AVGCLASSSIZESta"), -contains("AVGCLASSSIZEDist"), -one_of("ROE","COUNTYCODE","DISTRICT","TYPE", "DistWhPct", "DistBlPct", "DistHispPct", "DistAsiPct", "DistNhopiPct", "DistNatPct", "DistTomRPct", "DistTotEnroll", "StaWhPct", "StaBlPct", "StaHispPct", "StaAsiPct", "StaNhopiPct", "StaNatPct", "StaTomRPct", "StaTotEnroll", "TotSchDAYSDist", "TotSchDAYSSta", "PctREADYFORCollCoursesDist",  "PctREADYFORCollCoursesSta") )


rc14 <- rc14 %>% select(-contains("Coming"), -contains("PctOFStudsNOTTAKING"), -contains("Nhopi"), -contains("TomR"), -contains("StaPct"), -contains("DistPct"), -contains("EnrollFORGR"), -contains("DistGR"), -contains("DistEnroll"),-contains("NumSta"), -contains("StaEnroll"), -contains("Subr"), -contains("MINPERDAY"), -contains("DistDOLLAR"), -contains("EnrollIN"), -contains("ISAT"), -contains("DistBELOW"), -contains("DistMeet"), -contains("Distexceed"), -contains("DistAcadWarn"), -contains("StaBELOW"), -contains("StaMeet"), -contains("Staexceed"), -contains("StaAcadWarn"),  -contains("SCORE"), -contains("SchAcadWarn"), -contains("SchBELOW"), -contains("SchMeet"), -contains("Schexceed"), -contains("PROGRESSING"), -contains("ATTEMPTING"),-contains("FORMeetAND"), -contains("ATTAINING"), -contains("EMERGING"), -contains("PROFICIENT"), -contains("BASIC"), -contains("ADVANCED"), -contains("ParticipatRATE"), -contains("MAKINGAYP"), -contains("Readtest"), -contains("TAKINGMATHTESTS"), -contains("OTHERINDICATO"), -contains("IMPROVEMENT"), -contains("DOLLAR"), -contains("EXPEND"), -contains("SchSINTHESta"), -contains("DistSINTHESta"), -contains("SchSINTHEDist"), -contains("PctMult"), -contains("PctNhopi"), -contains("PctNat"), -contains("ACTCOMP"), -contains("LEGISLATIVE"), -contains("IEP"), -contains("AVGCLASSSIZESta"), -contains("AVGCLASSSIZEDist"), -one_of("ROE","COUNTYCODE","DISTRICT","TYPE", "DistWhPct", "DistBlPct", "DistHispPct", "DistAsiPct", "DistNhopiPct", "DistNatPct", "DistTomRPct", "DistTotEnroll", "StaWhPct", "StaBlPct", "StaHispPct", "StaAsiPct", "StaNhopiPct", "StaNatPct", "StaTomRPct", "StaTotEnroll", "TotSchDAYSDist", "TotSchDAYSSta", "PctREADYFORCollCoursesDist",  "PctREADYFORCollCoursesSta") )



```




```{r}
labels(rc14)[2]
```
```{r}
full_term <- plyr::rbind.fill(full_term, rc13, rc14)
```


```{r}
library(tm)
read <- tm::readPDF(control = list(text = "-layout"))
schoolsByWard <- Corpus(URISource(here::here("data", "Schools_by_Ward_2012.pdf")), readerControl = list(reader = read))
schoolsByWard_content <- content(schoolsByWard[[1]])
schoolsByWard_content <- unlist(schoolsByWard_content <- strsplit(schoolsByWard_content, "\n"))

```

```{r}
page_breaks <- grep("02/05/2019", schoolsByWard_content)
schoolsByWard_content <- schoolsByWard_content[- (page_breaks)]
```

```{r}
# Remove headers
header_rows <- grep("^Schools by", schoolsByWard_content) 

schoolsByWard_content <- schoolsByWard_content[- (header_rows)]

subtitle_rows <- grep("^Based on", schoolsByWard_content) 
schoolsByWard_content <- schoolsByWard_content[- (subtitle_rows)]
```


```{r}
# add delimiters to PDF text corpus
schoolsByWard <-  gsub(" {2,100}", ";", schoolsByWard_content)
```

```{r}
# Concatenate cut-off rows
to_remove <- list()

for (i in 1:length(schoolsByWard)) {
  if (str_count(schoolsByWard[i],";") == 3 ) {
    schoolsByWard[[i]] = gsub("Ave ", "Ave;", schoolsByWard[[i]])
    schoolsByWard[[i]] = gsub("Blvd ", "Blvd;", schoolsByWard[[i]])
    
  } else if (str_count(schoolsByWard[i],";") < 3 ) {
    if (";Dr" %in% schoolsByWard[[i]] | ";Ave" %in% schoolsByWard[[i]]) {
      schoolsByWard[[i]] = paste(str_match(schoolsByWard[i-1], '^(?:[^;]*;){3}([^;]*)'), " ", gsub(";", "", schoolsByWard[[i]]), ";", str_match(schoolsByWard[i-1], '(?:[^;]*;){0}([^;]*)$'), sep="")[1]
      to_remove <- append(to_remove, i-1)
      
    } else {
    schoolsByWard[[i]] = paste(str_match(schoolsByWard[[i-1]], '^(?:[^;]*;){2}([^;]*)'), " ", gsub(";", "", str_match(schoolsByWard[[i]],'(?:[^;]*;)([^;][:alpha:]+[:space:]*){1,4}')), ";", str_match(schoolsByWard[[i-1]], '(?:[^;]*;){1}([^;]*)$'), sep="")[1]
    to_remove <- append(to_remove, i-1)
    }
  }
}

schoolsByWard <- schoolsByWard[-(unlist(to_remove))]
```



```{r}
schoolsByWard <-  read.table(text=schoolsByWard, sep=";", quote="", stringsAsFactors=FALSE, header = TRUE)
schoolsByWard <- schoolsByWard %>% select(-one_of('X'))
```


```{r}
formatBudget <- function(budget_df, year) {
  df_names <- colnames(budget_df)
  for (i in 1:length(df_names)) {
    
    if (str_detect(df_names[i], as.character(year))) {
       df_names[i] <-  gsub(paste("FY ",year," ", sep=""),"", df_names[i])
       df_names[i] <-  gsub(paste("FY",year," ", sep=""),"", df_names[i])
    } else if (str_detect(df_names[i], as.character(year - 1))) {
      df_names[i] <- gsub(paste("FY ",year - 1," ", sep=""),"Previous Year ", df_names[i])
      df_names[i] <- gsub(paste("FY",year - 1," ", sep=""),"Previous Year ", df_names[i])
    } else if (str_detect(df_names[i], as.character(year - 2))) {
      df_names[i] <- gsub(paste("FY ",year - 2," ", sep=""),"2 Yr Prior ", df_names[i])
      df_names[i] <- gsub(paste("FY",year - 2," ", sep=""),"2 Yr Prior ", df_names[i])
    } 
    
    if (str_detect(df_names[i], "Difference of")) { 
      df_names[i] <- str_match(df_names[i], "(.)+Difference")[1] 
      }
    if ((df_names[i] == "Budget") || (df_names[i] == "Positions") ) { 
      df_names[i] <- str_c(df_names[i], " Difference") 
      }
  } 
  return(df_names)
}
```




```{r warning=FALSE}
compileBudgets <- function(filename, year, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")) {
  
  budget_df <- read_xlsx(here::here("data", filename), col_names = TRUE, skip = 2,
                        col_types = col_types)
  budget_df <- budget_df %>% mutate(unitNum = gsub("U", "", Unit),
                                    YEAR=year)
  colnames(budget_df) <- formatBudget(budget_df, year)
  return(budget_df)
 }
```

```{r warning=FALSE}


bud13 <- compileBudgets("FY12-13 My Schools Report by Category by Unit RollUp.xlsx", 2013, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
bud14 <- compileBudgets("FY12-14 My Schools Report by Category by Unit RollUp.xlsx", 2014)
bud15 <- compileBudgets("FY13-15 My Schools Report by Category by Unit RollUp.xlsx", 2015)
bud16 <- compileBudgets("FY14-16 My Schools Report by Category by Unit RollUp.xlsx", 2016)
bud17 <- compileBudgets("FY15-17 My Schools Report by Category by Unit RollUp.xlsx", 2017, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
bud18 <- compileBudgets("FY16-18 My Schools Report by Category by Unit RollUp.xlsx", 2018)
bud19 <- compileBudgets("FY18-19 My Schools Report by Category by Unit RollUp.xlsx", 2019)
```



```{r}
all_budgets <- plyr::rbind.fill(bud13, bud14, bud15, bud16, bud17, bud18, bud19)
```


```{r}
all_budgets <- all_budgets %>% mutate(`Proposed Budget` = ifelse(is.na(`Proposed Budget`), `Approved Budget`, `Proposed Budget`),
                                      `Proposed Positions` = ifelse(is.na(`Proposed Positions`), `Approved Positions`, `Proposed Positions`))
# rm(bud13, bud14, bud15, bud16, bud17, bud18, bud19)
```


```{r}
# look at rows missing budget difference
all_budgets %>% filter(is.na(`Budget Difference`))
```


```{r message=FALSE, warning=FALSE}
# read in file with IDs to join from different sources
id_overlap <- read_csv(here::here("data", "Chicago_Public_Schools_-_School_Profile_Information_SY1617.csv"), col_names = TRUE)
id_overlap <- id_overlap %>% mutate(Finance_ID = as.character(Finance_ID))
```


```{r}
all_budgets <- left_join(all_budgets, id_overlap, by = c("unitNum" = "Finance_ID")) %>% 
  select( contains('_ID'), contains("long_name"),contains("address"), one_of(colnames(all_budgets)), contains("latitude"), contains("longitude"))
```

```{r}
all_budgets <- left_join(all_budgets, 
                         read_csv(here::here("data", "NEW_Chicago_Public_Schools_-_School_Profile_Information_SY1718.csv") %>% 
                                    mutate(Finance_ID = as.character(Finance_ID)), by = c("unitNum" = "Finance_ID"))) %>% 
                           select( contains('_ID'), contains("long_name"),contains("address"), one_of(colnames(all_budgets)), 
                                   contains("latitude"), contains("longitude"))
```

