---
title: "Chicago Public Schools Data Import"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```



```{r Housekeeping, echo=TRUE, message=FALSE, warning=FALSE, include=FALSE}
# Housekeeping (clear workspace, start output file, load packages)
# rm(list=ls())
library(Hmisc)
library(haven)
library(readxl)
library(lubridate)
library(tidyverse)
library(here)
```


```{r include=FALSE}
# Experiment with one file to write functions
# rc17Layout <- mutate(rc17Layout, descriptions = ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3)))
```

```{r include=FALSE}
# rc17Layout <- read_excel(here::here("data","RC17_layout.xlsx"), sheet="RC17", col_names=FALSE)
```

```{r include=FALSE}
# rc17Layout %>% filter(is.na(as.numeric(X__1)))
```

```{r warning=FALSE, include=FALSE}
# rc17Layout <- rc17Layout %>% filter(!is.na(as.numeric(X__1)))
```

```{r include=FALSE}
# rc17Layout %>% filter(!is.na(X__2))
```

```{r include=FALSE}
# rc17Layout <- rc17Layout %>% select(-one_of(c("X__2")))
```

```{r include=FALSE}
# rc17Layout <- mutate(rc17Layout, descriptions = ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3)))
```


```{r}
importReportCards <- function(file, year, layout) {
   repCard <- read.delim(here::here("data", file), header = FALSE, sep=";")
   print(paste("layout length: ", nrow(layout)))
   print(paste("report card columns: ", ncol(repCard)))
   
   if (colnames(repCard) == nrow(layout)) {
      names(repCard) = layout %>% dplyr::select(X__6)
   } else if (ncol(repCard) > nrow(layout)) {
      name_vec = layout$descriptions
      names(repCard) <-  append(name_vec, sprintf("V%1d", 1:(ncol(repCard) - nrow(layout))))
   }
   
   cols = colnames(repCard)
   if ("DistNAME" %in% cols) {
      repCard <-  repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else if ("District" %in% cols) {
       repCard <-  repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else if ("DISTRICT NAME" %in% cols) {
       repCard <- repCard %>% filter(grepl("City of Chicago",`DISTRICT NAME`))
   } else {
     print("Error: Check District column name")
   }

   id_info = c("SCHOOL ID (R-C-D-T-S)", "SCHOOL TYPE CODE (0,1,2,C)", "SCHOOL NAME", "DISTRICT NAME", "CITY", "COUNTY")
   repCard <- repCard %>% dplyr::select(id_info, contains("SCHOOL"))
   repCard <-  mutate(repCard, YEAR = year)
   return(repCard)
   } 
```



```{r}
processLayout <- function(file, sheet, colnames) {
  layout = read_excel(here::here("data", file), sheet=sheet, col_names=colnames)
  layout = layout %>% filter(!is.na(as.numeric(X__1)))
  layout = layout %>% dplyr::select(-one_of(c("X__2")))
  layout = mutate(layout, descriptions = toupper(ifelse(is.na(X__3),X__6, paste(X__6, " - ", X__3))))
  return(layout)
}
```



```{r}
rc_key_phrases <- c("Summative Designation", "Low-Income", "Enrollment", "School Days", "Attendance Rate", "Truancy",	"Truant", "Truants", "Dropout", 'Dropout Rate', "DROPOUT RATE SCHOOL %", "Graduation Rate", "Grad Rate", "Class Size", "Teaching Exp", "Teacher Exp", "Teaching Exp.", "Teacher Exp.", "Teaching Experience", "Provisional Credentials", "Teacher Ratio", "Admin Ratio", "Pupil-Teacher", "Pupil-Admin", "Teacher Avg Salary", "Admin Avg Salary", "Teacher Retention", "Principal Turnover",	"Teacher Attendace", "Teacher Evaluation", "AP Classes", "AP Exams")
rc_key_phrases <- sapply(rc_key_phrases, toupper)
```


```{r}
id_info <- c("YEAR", "SCHOOL ID (R-C-D-T-S)", "SCHOOL NAME", "DISTRICT NAME", "CITY", "COUNTY", "SCHOOL TYPE NAME", "GRADES IN SCHOOL", "SCHOOL - WHITE %", "SCHOOL - BLACK %", "SCHOOL - HISPANIC %", "SCHOOL - ASIAN %", "LOW-INCOME SCHOOL %")
```


```{r include=FALSE}
# data exploration 
rc15Layout <- processLayout(file="RC15-layout.xlsx", sheet="RC15", colnames=FALSE)
```

```{r include=FALSE}
rc15 <- importReportCards("rc15.txt", "2015", rc15Layout)
```

```{r}
rc15 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```

```{r}
rc16Layout <- processLayout(file="RC16-layout.xlsx", sheet="RC16", colnames=FALSE)
```

```{r}
rc16 <- importReportCards("rc16.txt", "2016", rc16Layout)
```

```{r}
rc16 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
rc17Layout <- processLayout(file="RC17_layout.xlsx", sheet="RC17", colnames=FALSE)
```

```{r}
rc17 <- importReportCards("rc17.txt", "2017", rc16Layout)
```

```{r}
rc17 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
rc15 <- rc15 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
rc16 <- rc16 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
rc17 <- rc17 %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")))
```


```{r}
ncol(rc15)
ncol(rc16)
ncol(rc17)
```


```{r}
full_term <- plyr::rbind.fill(rc15, rc16, rc17)
```

```{r}
rc18 <- read_xlsx(here::here("data", "Report-Card-Public-Data-Set.xlsx"), sheet = "General")
rc18 <- mutate(rc18, YEAR="2018")
colnames(rc18) <- sapply(colnames(rc18), toupper)
```

```{r include=FALSE}
rc18 <- rc18 %>% rename(
  "SCHOOL ID (R-C-D-T-S)" = "RCDTS",
  "SCHOOL TYPE NAME" = "SCHOOL TYPE",
  "GRADES IN SCHOOL" = "GRADES SERVED",
  "DISTRICT NAME" = "DISTRICT",
  "SCHOOL - WHITE %" = "STUDENT ENROLLMENT - WHITE %", 
  "SCHOOL - BLACK %" = "STUDENT ENROLLMENT - BLACK OR AFRICAN AMERICAN %",
  "SCHOOL - HISPANIC %" = "STUDENT ENROLLMENT - HISPANIC OR LATINO %",
  "SCHOOL - ASIAN %" = "STUDENT ENROLLMENT - ASIAN %",
  "SCHOOL TOTAL ENROLLMENT"  = "STUDENT ENROLLMENT - TOTAL",
  "LOW-INCOME SCHOOL %" = "STUDENT ENROLLMENT - LOW INCOME %",
  "TOTAL SCHOOL DAYS - SCHOOL" = "TOTAL NUMBER OF SCHOOL DAYS",
  "ATTENDANCE RATE SCHOOL %  -  ALL" = "STUDENT ATTENDANCE RATE",
  "ATTENDANCE RATE SCHOOL %  -  MALE" = "STUDENT ATTENDANCE RATE - MALE",
  "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "STUDENT ATTENDANCE RATE - FEMALE",
  "ATTENDANCE RATE SCHOOL %  -  WHITE" = "STUDENT ATTENDANCE RATE - WHITE",
  "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "STUDENT ATTENDANCE RATE - HISPANIC OR LATINO",
  "CHRONIC TRUANTS RATE SCHOOL %" = "STUDENT CHRONIC TRUANCY RATE",
  "ATTENDANCE RATE SCHOOL %  -  BLACK" = "STUDENT ATTENDANCE RATE - BLACK OR AFRICAN AMERICAN",
  "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "STUDENT ATTENDANCE RATE - ASIAN",
  "CHRONIC TRUANTS # - SCHOOL" = "CHRONICALLY TRUANT STUDENTS",
  "DROPOUT RATE  SCHOOL %" = "HIGH SCHOOL DROPOUT RATE - TOTAL",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - TOTAL",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - MALE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - FEMALE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - WHITE",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - ASIAN",
  "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HIGH SCHOOL 4-YEAR GRADUATION RATE - LOW INCOME",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - TOTAL",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - MALE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - FEMALE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - WHITE",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - ASIAN",
  "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HIGH SCHOOL 5-YEAR GRADUATION RATE - LOW INCOME",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  ALL" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - TOTAL",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  MALE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - MALE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - FEMALE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - WHITE",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - BLACK OR AFRICAN AMERICAN",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - HISPANIC OR LATINO",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HIGH SCHOOL 6-YEAR GRADUATION RATE - ASIAN",
  "HS 6-YEAR GRAD RATE SCHOOL %  -  LOW INCOME"  = "HIGH SCHOOL 6-YEAR GRADUATION RATE - LOW INCOME",
  "AVG CLASS SIZE - SCHOOL (KG)" = "AVG CLASS SIZE - KINDERGARTEN",
  "AVG CLASS SIZE - SCHOOL (GR1)" = "AVG CLASS SIZE - 1",
  "AVG CLASS SIZE - SCHOOL (GR2)" = "AVG CLASS SIZE - 2",
  "AVG CLASS SIZE - SCHOOL (GR3)" = "AVG CLASS SIZE - 3",
  "AVG CLASS SIZE - SCHOOL (GR4)" = "AVG CLASS SIZE - 4",
  "AVG CLASS SIZE - SCHOOL (GR5)" = "AVG CLASS SIZE - 5",
  "AVG CLASS SIZE - SCHOOL (GR6)" = "AVG CLASS SIZE - 6",
  "AVG CLASS SIZE - SCHOOL (GR7)" = "AVG CLASS SIZE - 7",
  "AVG CLASS SIZE - SCHOOL (GR8)" = "AVG CLASS SIZE - 8",
  "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVG CLASS SIZE - HIGH SCHOOL",
  "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "AVG CLASS SIZE – ALL GRADES",
  "TEACHER RETENTION RATE (SCHOOL)" = "TEACHER RETENTION RATE",
  "# OF PRINCIPAL TURNOVER WITHIN 6 YEARS (SCHOOL)"  = "PRINCIPAL TURNOVER WITHIN 6 YEARS",
  "TEACHER ATTENDANCE RATE (SCHOOL)  -  ALL" = "TEACHER ATTENDACE RATE",
  "# OF CTE ENROLLMENT (SCHOOL)" = "# OF CTE ENROLLMENT",
  "# OF AP EXAMS TAKEN BY GRADE 10 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 10",
  "# OF AP EXAMS PASSED BY GRADE 10 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 10",
  "# OF GRADE 10 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 10",
  "# OF AP EXAMS TAKEN BY GRADE 11 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 11",
  "# OF AP EXAMS PASSED BY GRADE 11 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 11",
  "# OF GRADE 11 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 11",
  "# OF GRADE 11 STUDENTS PASSED ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO PASSED ONE ORE MORE AP EXAMS GRADE 11",
  "# OF AP EXAMS TAKEN BY GRADE 12 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS GRADE 12",
  "# OF AP EXAMS PASSED BY GRADE 12 STUDENTS (SCHOOL)" = "TOTAL AP EXAMS RESULTING IN COLLEGE CREDIT GRADE 12",
  "# OF GRADE 12 STUDENTS TOOK ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO TOOK ONE ORE MORE AP EXAMS GRADE 12",
  "# OF GRADE 12 STUDENTS PASSED ONE OR MORE AP EXAMS (SCHOOL)" = "NUMBER OF STUDENTS WHO PASSED ONE ORE MORE AP EXAMS GRADE 12"
  )

rc18 %>% filter(grepl("City of Chicago", `DISTRICT NAME`)) %>% dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")), -contains("IEP"), -contains("TWO OR MORE"), -contains("OTHER"), -contains("ALASKA"), -contains("NUMBER EL"), -contains(" - SUBREGION"), -contains(" - DISTRICT"))
```

```{r}
rc18 <- rc18 %>% filter(grepl("City of Chicago", `DISTRICT NAME`)) %>% 
  dplyr::select(id_info, matches(paste(rc_key_phrases,collapse="|")), -contains("IEP"), -contains("TWO OR MORE"), -contains("OTHER"), -contains("ALASKA"), -contains("NUMBER EL"), -contains(" - SUBREGION"), -contains(" - DISTRICT"))
```

```{r include=FALSE}
# check for column name changes from previous years
setdiff(colnames(full_term), colnames(rc18))
```

```{r include=FALSE}
# check for newly introduced columns in 2018
setdiff(colnames(rc18), colnames(full_term))
```


```{r}
full_term <- plyr::rbind.fill(full_term, rc18)
```


```{r include=FALSE}
# attempt at fuzzzy matching between 2018 and previous years
# col_check <- data.frame(name2018=colnames(rc18),
#                  prevname=NA*length(colnames(rc18)), 
#                  stringsAsFactors=FALSE) 
# for(i in 1:length(col_check$name2018) ) {
#    x <- agrep(pattern=col_check$name2018[i], x=colnames(rc_2015_to_2018),
#    ignore.case=TRUE, value=TRUE,
#    max.distance = 0.01, useBytes = TRUE)
#    x <- paste0(x,"")
#    col_check$prevname[i] <- x
# }
# View(col_check)
```

```{r}
rc13 <- haven::read_sas(here::here("data", "rc13-sas-data", "rc13-sas-data.sas7bdat"))
rc14 <- haven::read_sas(here::here("data", "rc14-sas-data", "rc14-sas-data.sas7bdat"))
```

```{r}
# dim(rc13 %>% filter(grepl("City of Chicago", DistNAME)))
# dim(rc14 %>% filter(grepl("City of Chicago", DistNAME)))
```
```{r}
rc13 <- rc13 %>% filter(grepl("City of Chicago", DistNAME))
rc14 <- rc14 %>% filter(grepl("City of Chicago", DistNAME))
rc13 <- mutate(rc13, YEAR = "2013")
rc14 <- mutate(rc13, YEAR = "2014")
```


```{r}

rc13 <- rc13 %>% rename("SCHOOL ID (R-C-D-T-S)" = "SchRcdts",
                "SCHOOL TYPE NAME" = "SchTYPENAME",
                "GRADES IN SCHOOL" = "GRSINSch",
                "SCHOOL NAME" = "SchNAME",
                "DISTRICT NAME" = "DistNAME",
                "SCHOOL - WHITE %" = "SchWhPct", 
                "SCHOOL - BLACK %" = "SchBlPct",
                "SCHOOL - HISPANIC %" = "SchHispPct",
                "SCHOOL - ASIAN %" = "SchAsiPct",
                "SCHOOL TOTAL ENROLLMENT"  = "SchTotEnroll",
                "LOW-INCOME SCHOOL %" = "LowIncSchPct",
                "TOTAL SCHOOL DAYS - SCHOOL" = "TotSchDAYSSch",
                "ATTENDANCE RATE SCHOOL %  -  ALL" = "AttendRATESchPctALL",
                "ATTENDANCE RATE SCHOOL %  -  MALE" = "AttendRATESchPctMALE",
                "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "AttendRATESchPctFem",
                "ATTENDANCE RATE SCHOOL %  -  WHITE" = "AttendRATESchPctWh",
                "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "AttendRATESchPctHisp",
                "ATTENDANCE RATE SCHOOL %  -  BLACK" = "AttendRATESchPctBl",
                "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "AttendRATESchPctAsi",
                "CHRONIC TRUANTS # - SCHOOL" = "CHRONICTRUANTSNumSch",
                "CHRONIC TRUANTS RATE SCHOOL %" = "CHRONICTRUANTSRATESchPct",
                "DROPOUT RATE  SCHOOL %" = "DROPOUTRATESchPct",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS5YrGRADRATESchPctALL",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS4YrGRADRATESchPctALL",
                "AVG CLASS SIZE - SCHOOL (KG)" = "AVGCLASSSIZESchKG",
                "AVG CLASS SIZE - SCHOOL (GR1)" = "AVGCLASSSIZESchGR1",
                "AVG CLASS SIZE - SCHOOL (GR2)" = "AVGCLASSSIZESchGR2",
                "AVG CLASS SIZE - SCHOOL (GR3)" = "AVGCLASSSIZESchGR3",
                "AVG CLASS SIZE - SCHOOL (GR4)" = "AVGCLASSSIZESchGR4",
                "AVG CLASS SIZE - SCHOOL (GR5)" = "AVGCLASSSIZESchGR5",
                "AVG CLASS SIZE - SCHOOL (GR6)" = "AVGCLASSSIZESchGR6",
                "AVG CLASS SIZE - SCHOOL (GR7)" = "AVGCLASSSIZESchGR7",
                "AVG CLASS SIZE - SCHOOL (GR8)" = "AVGCLASSSIZESchGR8",
                "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVGCLASSSIZESchHS",
                "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "OVERALLAvgCLASSSIZESch",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS4YrGRADRATESchPctMALE",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS4YrGRADRATESchPctFem",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS4YrGRADRATESchPctWh",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS4YrGRADRATESchPctBl",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS4YrGRADRATESchPctHisp",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS4YrGRADRATESchPctAsi",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS4YrGRADRATESchPctLowInc",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS5YrGRADRATESchPctMALE",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS5YrGRADRATESchPctFem",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS5YrGRADRATESchPctWh",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS5YrGRADRATESchPctBl",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS5YrGRADRATESchPctHisp",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS5YrGRADRATESchPctAsi",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS5YrGRADRATESchPctLowInc")

rc14 <- rc14 %>%  rename("SCHOOL ID (R-C-D-T-S)" = "SchRcdts",
                "SCHOOL TYPE NAME" = "SchTYPENAME",
                "GRADES IN SCHOOL" = "GRSINSch",
                "SCHOOL NAME" = "SchNAME",
                "DISTRICT NAME" = "DistNAME",
                "SCHOOL - WHITE %" = "SchWhPct", 
                "SCHOOL - BLACK %" = "SchBlPct",
                "SCHOOL - HISPANIC %" = "SchHispPct",
                "SCHOOL - ASIAN %" = "SchAsiPct",
                "SCHOOL TOTAL ENROLLMENT"  = "SchTotEnroll",
                "LOW-INCOME SCHOOL %" = "LowIncSchPct",
                "TOTAL SCHOOL DAYS - SCHOOL" = "TotSchDAYSSch",
                "ATTENDANCE RATE SCHOOL %  -  ALL" = "AttendRATESchPctALL",
                "ATTENDANCE RATE SCHOOL %  -  MALE" = "AttendRATESchPctMALE",
                "ATTENDANCE RATE SCHOOL %  -  FEMALE" = "AttendRATESchPctFem",
                "ATTENDANCE RATE SCHOOL %  -  WHITE" = "AttendRATESchPctWh",
                "ATTENDANCE RATE SCHOOL %  -  HISPANIC" = "AttendRATESchPctHisp",
                "ATTENDANCE RATE SCHOOL %  -  BLACK" = "AttendRATESchPctBl",
                "ATTENDANCE RATE SCHOOL %  -  ASIAN" = "AttendRATESchPctAsi",
                "CHRONIC TRUANTS # - SCHOOL" = "CHRONICTRUANTSNumSch",
                "CHRONIC TRUANTS RATE SCHOOL %" = "CHRONICTRUANTSRATESchPct",
                "DROPOUT RATE  SCHOOL %" = "DROPOUTRATESchPct",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS5YrGRADRATESchPctALL",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ALL" = "HS4YrGRADRATESchPctALL",
                "AVG CLASS SIZE - SCHOOL (KG)" = "AVGCLASSSIZESchKG",
                "AVG CLASS SIZE - SCHOOL (GR1)" = "AVGCLASSSIZESchGR1",
                "AVG CLASS SIZE - SCHOOL (GR2)" = "AVGCLASSSIZESchGR2",
                "AVG CLASS SIZE - SCHOOL (GR3)" = "AVGCLASSSIZESchGR3",
                "AVG CLASS SIZE - SCHOOL (GR4)" = "AVGCLASSSIZESchGR4",
                "AVG CLASS SIZE - SCHOOL (GR5)" = "AVGCLASSSIZESchGR5",
                "AVG CLASS SIZE - SCHOOL (GR6)" = "AVGCLASSSIZESchGR6",
                "AVG CLASS SIZE - SCHOOL (GR7)" = "AVGCLASSSIZESchGR7",
                "AVG CLASS SIZE - SCHOOL (GR8)" = "AVGCLASSSIZESchGR8",
                "AVG CLASS SIZE - SCHOOL (H.S.)" = "AVGCLASSSIZESchHS",
                "OVERALL AVERAGE CLASS SIZE - SCHOOL" = "OVERALLAvgCLASSSIZESch",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS4YrGRADRATESchPctMALE",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS4YrGRADRATESchPctFem",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS4YrGRADRATESchPctWh",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS4YrGRADRATESchPctBl",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS4YrGRADRATESchPctHisp",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS4YrGRADRATESchPctAsi",
                "HS 4-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS4YrGRADRATESchPctLowInc",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  MALE" = "HS5YrGRADRATESchPctMALE",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  FEMALE" = "HS5YrGRADRATESchPctFem",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  WHITE" = "HS5YrGRADRATESchPctWh",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  BLACK" = "HS5YrGRADRATESchPctBl",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  HISPANIC" = "HS5YrGRADRATESchPctHisp",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  ASIAN" = "HS5YrGRADRATESchPctAsi",
                "HS 5-YEAR GRAD RATE SCHOOL %  -  LOW INCOME" = "HS5YrGRADRATESchPctLowInc")


```




```{r}
setdiff(sapply(colnames(rc13), toupper), sapply(colnames(rc14), toupper))
```


```{r}
# double-check "COMING SOON" columns are all NA in 2013 data
rc13 %>% dplyr::select(contains("Coming")) %>% summarise_all(funs(n_distinct(.)))
```


```{r}
# double-check "COMING SOON" columns are all NA in 2014 data
rc14 %>% dplyr::select(contains("Comming")) %>% summarise_all(funs(n_distinct(.)))
```


```{r}
# remove columns with non-pertinent info
rc13 <- rc13 %>%  dplyr::select(-contains("Coming"), -contains("PctOFStudsNOTTAKING"), -contains("Nhopi"), -contains("TomR"), -contains("StaPct"), -contains("DistPct"), -contains("EnrollFORGR"), -contains("DistGR"), -contains("DistEnroll"),-contains("NumSta"), -contains("StaEnroll"), -contains("Subr"), -contains("MINPERDAY"), -contains("DistDOLLAR"), -contains("EnrollIN"), -contains("ISAT"), -contains("DistBELOW"), -contains("DistMeet"), -contains("Distexceed"), -contains("DistAcadWarn"), -contains("StaBELOW"), -contains("StaMeet"), -contains("Staexceed"), -contains("StaAcadWarn"),  -contains("SCORE"), -contains("SchAcadWarn"), -contains("SchBELOW"), -contains("SchMeet"), -contains("Schexceed"), -contains("PROGRESSING"), -contains("ATTEMPTING"),-contains("FORMeetAND"), -contains("ATTAINING"), -contains("EMERGING"), -contains("PROFICIENT"), -contains("BASIC"), -contains("ADVANCED"), -contains("ParticipatRATE"), -contains("MAKINGAYP"), -contains("Readtest"), -contains("TAKINGMATHTESTS"), -contains("OTHERINDICATO"), -contains("IMPROVEMENT"), -contains("DOLLAR"), -contains("EXPEND"), -contains("SchSINTHESta"), -contains("DistSINTHESta"), -contains("SchSINTHEDist"), -contains("PctMult"), -contains("PctNhopi"), -contains("PctNat"), -contains("ACTCOMP"), -contains("LEGISLATIVE"), -contains("IEP"), -contains("AVGCLASSSIZESta"), -contains("AVGCLASSSIZEDist"), -one_of("ROE","COUNTYCODE","DISTRICT","TYPE", "DistWhPct", "DistBlPct", "DistHispPct", "DistAsiPct", "DistNhopiPct", "DistNatPct", "DistTomRPct", "DistTotEnroll", "StaWhPct", "StaBlPct", "StaHispPct", "StaAsiPct", "StaNhopiPct", "StaNatPct", "StaTomRPct", "StaTotEnroll", "TotSchDAYSDist", "TotSchDAYSSta", "PctREADYFORCollCoursesDist",  "PctREADYFORCollCoursesSta") )


rc14 <- rc14 %>% dplyr::select(-contains("Coming"), -contains("PctOFStudsNOTTAKING"), -contains("Nhopi"), -contains("TomR"), -contains("StaPct"), -contains("DistPct"), -contains("EnrollFORGR"), -contains("DistGR"), -contains("DistEnroll"),-contains("NumSta"), -contains("StaEnroll"), -contains("Subr"), -contains("MINPERDAY"), -contains("DistDOLLAR"), -contains("EnrollIN"), -contains("ISAT"), -contains("DistBELOW"), -contains("DistMeet"), -contains("Distexceed"), -contains("DistAcadWarn"), -contains("StaBELOW"), -contains("StaMeet"), -contains("Staexceed"), -contains("StaAcadWarn"),  -contains("SCORE"), -contains("SchAcadWarn"), -contains("SchBELOW"), -contains("SchMeet"), -contains("Schexceed"), -contains("PROGRESSING"), -contains("ATTEMPTING"),-contains("FORMeetAND"), -contains("ATTAINING"), -contains("EMERGING"), -contains("PROFICIENT"), -contains("BASIC"), -contains("ADVANCED"), -contains("ParticipatRATE"), -contains("MAKINGAYP"), -contains("Readtest"), -contains("TAKINGMATHTESTS"), -contains("OTHERINDICATO"), -contains("IMPROVEMENT"), -contains("DOLLAR"), -contains("EXPEND"), -contains("SchSINTHESta"), -contains("DistSINTHESta"), -contains("SchSINTHEDist"), -contains("PctMult"), -contains("PctNhopi"), -contains("PctNat"), -contains("ACTCOMP"), -contains("LEGISLATIVE"), -contains("IEP"), -contains("AVGCLASSSIZESta"), -contains("AVGCLASSSIZEDist"), -one_of("ROE","COUNTYCODE","DISTRICT","TYPE", "DistWhPct", "DistBlPct", "DistHispPct", "DistAsiPct", "DistNhopiPct", "DistNatPct", "DistTomRPct", "DistTotEnroll", "StaWhPct", "StaBlPct", "StaHispPct", "StaAsiPct", "StaNhopiPct", "StaNatPct", "StaTomRPct", "StaTotEnroll", "TotSchDAYSDist", "TotSchDAYSSta", "PctREADYFORCollCoursesDist",  "PctREADYFORCollCoursesSta") )



```




```{r}
full_term <- plyr::rbind.fill(full_term, rc13, rc14)

saveRDS(full_term, file = here::here("data", "full_term.Rda"))
# 
```


```{r}
library(tm)
read <- tm::readPDF(control = list(text = "-layout"))
schoolsByWard <- Corpus(URISource(here::here("data", "Schools_by_Ward_2012.pdf")), readerControl = list(reader = read))
schoolsByWard_content <- content(schoolsByWard[[1]])
schoolsByWard_content <- unlist(schoolsByWard_content <- strsplit(schoolsByWard_content, "\n"))

```

```{r}
page_breaks <- grep("02/05/2019", schoolsByWard_content)
schoolsByWard_content <- schoolsByWard_content[- (page_breaks)]
```

```{r}
# Remove headers
header_rows <- grep("^Schools by", schoolsByWard_content) 

schoolsByWard_content <- schoolsByWard_content[- (header_rows)]

subtitle_rows <- grep("^Based on", schoolsByWard_content) 
schoolsByWard_content <- schoolsByWard_content[- (subtitle_rows)]
```


```{r}
# add delimiters to PDF text corpus
schoolsByWard <-  gsub(" {2,100}", ";", schoolsByWard_content)
```

```{r}
# Concatenate cut-off rows
to_remove <- list()

for (i in 1:length(schoolsByWard)) {
  if (str_count(schoolsByWard[i],";") == 3 ) {
    schoolsByWard[[i]] = gsub("Ave ", "Ave;", schoolsByWard[[i]])
    schoolsByWard[[i]] = gsub("Blvd ", "Blvd;", schoolsByWard[[i]])
    
  } else if (str_count(schoolsByWard[i],";") < 3 ) {
    if (";Dr" %in% schoolsByWard[[i]] | ";Ave" %in% schoolsByWard[[i]]) {
      schoolsByWard[[i]] = paste(str_match(schoolsByWard[i-1], '^(?:[^;]*;){3}([^;]*)'), " ", gsub(";", "", schoolsByWard[[i]]), ";", str_match(schoolsByWard[i-1], '(?:[^;]*;){0}([^;]*)$'), sep="")[1]
      to_remove <- append(to_remove, i-1)
      
    } else {
    schoolsByWard[[i]] = paste(str_match(schoolsByWard[[i-1]], '^(?:[^;]*;){2}([^;]*)'), " ", gsub(";", "", str_match(schoolsByWard[[i]],'(?:[^;]*;)([^;][:alpha:]+[:space:]*){1,4}')), ";", str_match(schoolsByWard[[i-1]], '(?:[^;]*;){1}([^;]*)$'), sep="")[1]
    to_remove <- append(to_remove, i-1)
    }
  }
}

schoolsByWard <- schoolsByWard[-(unlist(to_remove))]
```



```{r}
schoolsByWard <-  read.table(text=schoolsByWard, sep=";", quote="", stringsAsFactors=FALSE, header = TRUE)
schoolsByWard <- schoolsByWard %>% dplyr::select(-one_of('X'))

saveRDS(schoolsByWard, file = here::here("data", "schoolsByWard.Rda"))
# 
```


```{r}
formatBudget <- function(budget_df, year) {
  df_names <- colnames(budget_df)
  for (i in 1:length(df_names)) {
    
    if (str_detect(df_names[i], as.character(year))) {
       df_names[i] <-  gsub(paste("FY ",year," ", sep=""),"", df_names[i])
       df_names[i] <-  gsub(paste("FY",year," ", sep=""),"", df_names[i])
    } else if (str_detect(df_names[i], as.character(year - 1))) {
      df_names[i] <- gsub(paste("FY ",year - 1," ", sep=""),"Previous Year ", df_names[i])
      df_names[i] <- gsub(paste("FY",year - 1," ", sep=""),"Previous Year ", df_names[i])
    } else if (str_detect(df_names[i], as.character(year - 2))) {
      df_names[i] <- gsub(paste("FY ",year - 2," ", sep=""),"2 Yr Prior ", df_names[i])
      df_names[i] <- gsub(paste("FY",year - 2," ", sep=""),"2 Yr Prior ", df_names[i])
    } 
    
    if (str_detect(df_names[i], "Difference of")) { 
      df_names[i] <- str_match(df_names[i], "(.)+Difference")[1] 
      }
    if ((df_names[i] == "Budget") || (df_names[i] == "Positions") ) { 
      df_names[i] <- str_c(df_names[i], " Difference") 
      }
  } 
  return(df_names)
}
```




```{r warning=FALSE}
compileBudgets <- function(filename, year, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")) {
  
  budget_df <- read_xlsx(here::here("data", filename), col_names = TRUE, skip = 2,
                        col_types = col_types)
  budget_df <- budget_df %>% mutate(unitNum = gsub("U", "", Unit),
                                    YEAR=year)
  colnames(budget_df) <- formatBudget(budget_df, year)
  return(budget_df)
 }
```

```{r warning=FALSE}


bud13 <- compileBudgets("FY12-13 My Schools Report by Category by Unit RollUp.xlsx", 2013, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
bud14 <- compileBudgets("FY12-14 My Schools Report by Category by Unit RollUp.xlsx", 2014)
bud15 <- compileBudgets("FY13-15 My Schools Report by Category by Unit RollUp.xlsx", 2015)
bud16 <- compileBudgets("FY14-16 My Schools Report by Category by Unit RollUp.xlsx", 2016)
bud17 <- compileBudgets("FY15-17 My Schools Report by Category by Unit RollUp.xlsx", 2017, col_types=c("guess", "guess", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
bud18 <- compileBudgets("FY16-18 My Schools Report by Category by Unit RollUp.xlsx", 2018)
bud19 <- compileBudgets("FY18-19 My Schools Report by Category by Unit RollUp.xlsx", 2019)
```



```{r}
all_budgets <- plyr::rbind.fill(bud13, bud14, bud15, bud16, bud17, bud18, bud19)

```


```{r}
all_budgets <- all_budgets %>% mutate(`Proposed Budget` = ifelse(is.na(`Proposed Budget`), `Approved Budget`, `Proposed Budget`),
                                      `Proposed Positions` = ifelse(is.na(`Proposed Positions`), `Approved Positions`, `Proposed Positions`))
# rm(bud13, bud14, bud15, bud16, bud17, bud18, bud19)
saveRDS(all_budgets, file = here::here("data", "all_budgets.Rda"))
# 
```


```{r include=FALSE, eval=FALSE}
# look at rows missing budget difference
all_budgets %>% filter(is.na(`Budget Difference`))
```


```{r message=FALSE, warning=FALSE}
# read in file with IDs to join from different sources
id_overlap <- read_csv(here::here("data", "Chicago_Public_Schools_-_School_Profile_Information_SY1617.csv"), col_names = TRUE)
id_overlap18 <- read_csv(here::here("data", "NEW_Chicago_Public_Schools_-_School_Profile_Information_SY1718.csv"), col_names = TRUE)
id_overlap <- id_overlap %>% mutate(Finance_ID = as.character(Finance_ID))
id_overlap18 <- id_overlap18 %>% mutate(Finance_ID = as.character(Finance_ID))
# saveRDS(id_overlap, file = here::here("data", "id_overlap.Rda"))



```


```{r include=FALSE, eval=FALSE}
all_report_cards <-  readRDS(here::here("data", "full_term.Rda"))
id_overlap <-  readRDS(here::here("data", "id_overlap.Rda"))
all_budgets <-  readRDS(here::here("data", "all_budgets.Rda"))
schoolsByWard <-  readRDS(here::here("data", "schoolsByWard.Rda"))


schoolsByWard <- schoolsByWard %>% rename("School_ID" =  "School.ID", 
                      "Unit_Name" = "Name.of.School",
                      "Address" = "Street.Address")

# pull in IDs available from Chicago Data Portal (2017 SY)
all_budgets <- left_join(all_budgets, id_overlap, by = c("unitNum" = "Finance_ID")) %>% 
  dplyr::select( contains('_ID'), contains("long_name"),contains("address"), 
                 one_of(colnames(all_budgets)), contains("latitude"), contains("longitude"))
all_budgets <- all_budgets %>% rename("Unit_Name" = "Unit Name")

keep_albudgets_cols <- colnames(all_budgets)

# matching on finance unit number matches 4,444 of 8,189 rows (654 schools)
dim(all_budgets %>% filter(!is.na(School_ID)))
dim(all_budgets %>% filter(!is.na(School_ID)) %>% distinct(Unit))

#1462 unites in budget
all_budgets  %>% distinct(Unit)

# attempting to also match on school name only matches 1 more row
inner_join(all_budgets, 
          id_overlap %>% 
            dplyr::select(contains('_ID'), contains("Long_Name"), contains("Address"), contains("Latitude"), contains("Longitude")) , 
          by = c("Unit_Name" = "Long_Name")) 

```



```{r include=FALSE, eval=FALSE}
# devtools::install_github("dgrtwo/fuzzyjoin")
library(fuzzyjoin)
# 


check_this <- all_budgets%>% filter(!is.na(Unit_Name)) %>% left_join(schoolsByWard, by = "School_ID") %>%   filter(!is.na(`Unit Name`)) %>% 
  dplyr::select(YEAR, Unit_Name, "Unit Name", School_ID, Address.x, Address.y, contains(".x"), contains(".y")) 


unmatched <- all_budgets%>% filter(!is.na(Unit_Name)) %>% anti_join(schoolsByWard, by = "School_ID")  %>% filter(!is.na(School_ID)) %>% left_join(all_report_cards, by= c("School_Id"))

check_this <- all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_left_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 0.15, method="jw", distance_col = "distance") %>% 
  dplyr::select(YEAR,Unit_Name, `Unit Name`, School_ID.x, School_ID.y,  distance, Address.x, Address.y, Ward, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 0.15, method="osa") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address,  contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 0.15, method="lv") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 0.15, method="dl") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 0.15, method="jaccard") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name" ), max_dist = 0.15, method="cosine") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name" ), max_dist = 0.15, method="qgram") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 


all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name" ), max_dist = 0.15, method="lcs") %>% filter(YEAR==2014) %>% 
  dplyr::select(YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 

all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_semi_join(schoolsByWard, by = c(Unit_Name = "Unit Name" ), max_dist = 0.15, method="hamming") %>%  filter(YEAR==2014) %>% 
  dplyr::select(dist, YEAR, Unit_Name, School_ID, Address, contains(".x"), contains(".y")) 
# all_budgets %>% filter(!is.na(Unit_Name)) %>% stringdist_anti_join(schoolsByWard, by = c(Unit_Name = "Unit Name"), max_dist = 2) %>% 
#   dplyr::select(YEAR, School_ID, Unit_Name,  `Unit Name`, Address) 

# fuzzy_join(all_budgets, schoolsByWard, fuzzy = c("Unit Name", "Address"), w = c(0.8, 0.2))

# %>% 
#   dplyr::select("School_ID", "School.ID", "Unit Name", "Name.of.School", "Address", "Street.Address", "Ward")
```


```{r}
file_names <-dir("/Users/lorenh/Documents/Classes/winter_2019/data_vizualization_course/chicago-investment/data/rc_v2", 
                 pattern = '\\.csv', full.names = TRUE)

names(file_names) <- c("ES2013", "HS2013", "ES2014", "HS2014", "ALL2016", "ALL2017",  "ALL2018", "ALL2019")
file_names
```
```{r message=FALSE, warning=FALSE}
included_years <- c(2013, 2013, 2014, 2014, 2016, 2017, 2018, 2019)

ES2013 <- read_csv(file_names[1], col_names = TRUE) %>% mutate(YEAR = included_years[1])
HS2013 <- read_csv(file_names[2], col_names = TRUE) %>% mutate(YEAR = included_years[2])
ES2014 <- read_csv(file_names[3], col_names = TRUE) %>% mutate(YEAR = included_years[3])
HS2014 <- read_csv(file_names[4], col_names = TRUE) %>% mutate(YEAR = included_years[4])
ALL2016 <- read_csv(file_names[5], col_names = TRUE) %>% mutate(YEAR = included_years[5])
ALL2017 <- read_csv(file_names[6], col_names = TRUE) %>% mutate(YEAR = included_years[6])
ALL2018 <- read_csv(file_names[7], col_names = TRUE) %>% mutate(YEAR = included_years[7])
ALL2019 <- read_csv(file_names[8], col_names = TRUE) %>% mutate(YEAR = included_years[8])

ALL_SCHOOL_INFO <- bind_rows(ES2013, HS2013) %>% 
  bind_rows(ES2014 %>% mutate(`Blue Ribbon Award` = as.character(`Blue Ribbon Award`))) %>% 
  bind_rows(HS2014 %>% mutate(`Blue Ribbon Award` = as.character(`Blue Ribbon Award`))) %>% 
  bind_rows(ALL2016) %>% 
  bind_rows(ALL2017) %>%
  bind_rows(ALL2018 %>% mutate(`Chronic_Truancy_Pct` = as.character(`Chronic_Truancy_Pct`))) %>% 
  bind_rows(ALL2019 %>% 
              mutate(
                `School_Survey_Parent_Response_Rate_Avg_Pct` = as.character(`School_Survey_Parent_Response_Rate_Avg_Pct`),
                `Chronic_Truancy_Pct` = as.character(`Chronic_Truancy_Pct`)
                )
            ) 
```


```{r eval=FALSE, include=FALSE}
colnames(ALL_SCHOOL_INFO)
```


```{r}


ALL_SCHOOL_INFO <-  ALL_SCHOOL_INFO %>% 
  mutate(
   School_ID = ifelse(is.na(School_ID), `School ID`, School_ID),
   ZIP = ifelse(!is.na(ZIP), ZIP, 
                ifelse(!is.na(Zip), Zip, 
                ifelse(!is.na(`ZIP Code`), `ZIP Code`,
                ZIP) )),
   Longitude = ifelse(is.na(Longitude), School_Longitude,
                             Longitude),
   Latitude = ifelse(is.na(Latitude), School_Latitude,
                            Latitude),
   Address = ifelse(is.na(Address), `Street Address`,
                    Address),
   
   Long_Name = ifelse(!is.na(Long_Name), Long_Name,
               ifelse(!is.na(`School Name`),`School Name`,
               ifelse(!is.na(`Name of School`),`Name of School`,
                      Long_Name))),
   One_Year_Dropout_Rate_Year_2_Pct = ifelse(
         is.na(One_Year_Dropout_Rate_Year_2_Pct) & YEAR == 2013, 
         `One-Year DropOut Rate Percentage 2013`, One_Year_Dropout_Rate_Year_2_Pct),
   
  Student_Attendance_Year_2_Pct = ifelse(
        is.na(Student_Attendance_Year_2_Pct) & YEAR == 2013, `Student Attendance Percentage 2013`, Student_Attendance_Year_2_Pct),
  
Teacher_Attendance_Year_2_Pct = ifelse(
      is.na(Teacher_Attendance_Year_2_Pct) & YEAR == 2013, 
      `Teacher Attendance Percentage 2013`, Teacher_Attendance_Year_2_Pct))

# saveRDS(ALL_SCHOOL_INFO, file = here::here("data", "ALL_SCHOOL_INFO.Rda"))
# ALL_SCHOOL_INFO <-  readRDS(here::here("data", "ALL_SCHOOL_INFO.Rda"))

all_report_cards %>% distinct(`SCHOOL ID (R-C-D-T-S)`, `SCHOOL NAME`, `SCHOOL TYPE NAME`)  %>%
  write_csv("all_report_card_schools.csv")

```



```{r}
read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv"))
```

```{r message=FALSE, warning=FALSE, include=FALSE, eval=FALSE}
# 1462 unique schools in budgets dataframe
dim(all_budgets  %>% distinct(unitNum))

# 721 unique schools in report card dataframe
dim(all_report_cards  %>% distinct(`SCHOOL ID (R-C-D-T-S)`))

# 659 budget school Finance Unit Numbers with names matched to CPS School_IDs (comined w/ profile data)
dim(all_budgets %>% distinct(School_ID))

# 452 report card schools matched ID exactly from ID-matchup doc (tied to RCDTS and School ID)
inner_join(all_report_cards, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("SCHOOL ID (R-C-D-T-S)" = "SCHOOL ID (R-C-D-T-S)"))  %>% distinct(School_ID)

# 31 budget schools match name exactly on budgets df (tied to RCDTS and School ID)
inner_join(all_budgets %>% filter(!is.na(Long_Name)), all_report_cards %>% filter(!is.na(`SCHOOL NAME`)) %>% dplyr::select(`SCHOOL ID (R-C-D-T-S)`, `SCHOOL NAME`), by=c("Long_Name" = "SCHOOL NAME"))  %>% distinct(School_ID)

# double-check result: the 31 already included in 452 matching 
setdiff(
  unlist(inner_join(all_budgets %>% filter(!is.na(Long_Name)), all_report_cards %>% filter(!is.na(`SCHOOL NAME`)) %>% dplyr::select(`SCHOOL ID (R-C-D-T-S)`, `SCHOOL NAME`), by=c("Long_Name" = "SCHOOL NAME"))  %>% distinct(School_ID)),
        unlist(inner_join(all_report_cards, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("SCHOOL ID (R-C-D-T-S)" = "SCHOOL ID (R-C-D-T-S)"))  %>% distinct(School_ID))
               )


# 418 budget schools match ID exactly from ID-matchup doc (tied to RCDTS and School ID)
inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID)


# 402 budget schools match name exactly from ID-matchup doc (tied to RCDTS and School ID)
inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x)

# only 7 match by name but not ID
setdiff(
  # in this
  unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x)),
  # not in this
unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID))  
)

# 23 match by ID but not by name
setdiff(
 # in this
unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID)),
 # not in this
  unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x))
)


# 658 budget schools mactch names in CPS School_IDs (combined w/ ALL_SCHOOL_INFO df)
inner_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% dplyr::select(School_ID, Long_Name), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x) 

# 240 can be matched to names but not by ID 
length(setdiff(
  # in this
  unlist(inner_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% dplyr::select(School_ID, Long_Name), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x)) ,
    # not in this
  unlist(inner_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% dplyr::select(School_ID, Long_Name), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID.x))
  
  ))


# 240 can be matched to ID but not to name
length(setdiff(
  # in this
  unlist(inner_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% dplyr::select(School_ID, Long_Name), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID)),
  # not in this
  unlist(inner_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% dplyr::select(School_ID, Long_Name), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x))
  ))


# 7 matching on name not in mached by ID
length(setdiff(
  # in this
       unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("Long_Name" = "Long_Name"))  %>% distinct(School_ID.x)),
  # not in this
  unlist(inner_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>% filter(!is.na(School_ID)) %>% dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` ), by=c("School_ID" = "School_ID"))  %>% distinct(School_ID))

  ))

```

```{r eval=FALSE}
# join data tables for analysis

# add in additional matches from ALL_SCHOOL_INFO to get School IDs
all_budgets <- left_join(all_budgets, ALL_SCHOOL_INFO %>% filter(!is.na(Long_Name)) %>% 
                           dplyr::select(School_ID, Long_Name) %>% distinct(Long_Name), 
                         by=c("Long_Name" = "Long_Name"))


# add RCDTS to all_budgets for joining with report card data 
all_budgets <- left_join(all_budgets, read_csv(here::here("data", "rc_v2", "matchup_school_ids.csv")) %>%
                           filter(!is.na(School_ID)) %>% 
                           dplyr::select(School_ID, Long_Name, `SCHOOL ID (R-C-D-T-S)` )%>% 
                           distinct(School_ID, `SCHOOL ID (R-C-D-T-S)`) %>% group_by(School_ID) 
                         # filter out bad matches in doc (same ID matched to multiple RCDTS)
                         %>% filter(!n()>1), 
                         # match on School_ID
                         by=c("School_ID" = "School_ID")) 

all_budgets <- all_budgets %>% mutate(YEAR = as.factor(YEAR))
all_report_cards <- all_report_cards %>% mutate(YEAR = as.factor(YEAR))

school_data <- left_join(all_report_cards, all_budgets, by=c("SCHOOL ID (R-C-D-T-S)" = "SCHOOL ID (R-C-D-T-S)", "YEAR" = "YEAR"), na_matches="never") %>% dplyr::select(School_ID, everything())



# saveRDS(school_data, file = here::here("data", "combined_school_data.Rda"))

```


```{r message=FALSE}
# read in combined school report card and budget dataset
school_data <-  readRDS(here::here("data", "combined_school_data.Rda"))

# confirm all rows matched to a budget have "Proposed Budget column"
school_data %>% filter(!is.na(School_ID) & is.na(`Proposed Budget`))

  
# add ward to rows from schoolsByWard document parsed above
school_data <- left_join(school_data, schoolsByWard %>% dplyr::select(School_ID, WARD = Ward, NAME_WARD_JOIN = `Unit Name`), by=c("School_ID" = "School_ID")) %>% dplyr::select(School_ID, WARD, SCHOOL_NAME = `SCHOOL NAME`, NAME_WARD_JOIN, `Proposed Budget`, `SCHOOL TOTAL ENROLLMENT`, everything())

# calculate average spend per student
school_data <- school_data %>% 
  mutate(
    # remove commas from enrollment column and make sure it's numeric
    SCHOOL_TOTAL_ENROLLMENT = as.numeric(gsub(",","",`SCHOOL TOTAL ENROLLMENT`)),
    # calculate a basic average spend based on enrollment and budget for each row
    AVG_SPEND_PER_STUDENT = as.numeric(`Proposed Budget` / `SCHOOL TOTAL ENROLLMENT`),
   # ensure year columns are all numeric
   YEAR = as.numeric(YEAR),
   PREV_YR = as.numeric(YEAR) - 1,
   TWO_YR_PRIOR = as.numeric(YEAR) - 2,
   # remove trailing white space from school types column 
   `SCHOOL TYPE NAME` = str_trim(`SCHOOL TYPE NAME`),
   # make sure all charter schools are included in school types column
   `SCHOOL TYPE NAME` = ifelse(str_detect(pattern="C$", `SCHOOL ID (R-C-D-T-S)`),
                                "CHARTERSCH", `SCHOOL TYPE NAME`)) %>% 
  dplyr::select(YEAR, PREV_YR, TWO_YR_PRIOR, School_ID, WARD, NAME_WARD_JOIN, 
                CY_BUDGET = `Proposed Budget`, 
                SCHOOL_TOTAL_ENROLLMENT =  `SCHOOL TOTAL ENROLLMENT`,
                AVG_SPEND_PER_STUDENT, everything())

# add Chicago area based on matching generated from Chicago Open Data portal dataset 
# and UChicago community-area-to-Side matching
school_data <- left_join(school_data, read_csv(here::here("data", "wardSides.csv")),
                         by="WARD") %>% 
  dplyr::select(YEAR, PREV_YR, TWO_YR_PRIOR, School_ID, WARD, SIDE, everything())

    
# make sure all years have all school types
school_data %>% distinct(YEAR, `SCHOOL TYPE NAME`)
```


```{r fig.height=12, fig.width=15, message=FALSE, warning=FALSE}

  ggplot(school_data) +
  # geom_line(aes(x=AVG_SPEND_PER_STUDENT, y=as.factor(YEAR))) +
  geom_point(aes(x=AVG_SPEND_PER_STUDENT, y=as.factor(YEAR), 
                 color=SIDE, size=SCHOOL_TOTAL_ENROLLMENT)) +
  scale_size_continuous(range = c(6,10)) +
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))) 
```


```{r fig.height=12, fig.width=15, message=FALSE, warning=FALSE}    
# check whether there are schools which could be matched to ward, that aren't
school_data %>% filter(!is.na(School_Latitude) & is.na(WARD))

st_as_sf(
  # isolate school IDs, geolocation info (address, latitude, longitude)
  school_data %>% 
           dplyr::select(`SCHOOL ID (R-C-D-T-S)`, School_ID, `SCHOOL_NAME`, Address, School_Latitude, School_Longitude), 
         coords = c(School_Latitude, School_Longitude), 
  agr = c(`SCHOOL ID (R-C-D-T-S)` = "identity", 
          School_ID = "identity", 
          `SCHOOL_NAME` = "identity", 
          Address = "constant"))
```







```{r}
# enable mapping by max race in school
school_data <- left_join(school_data %>% 
                           dplyr::select(-predominant_race, -max_pct), 
                         school_data %>% 
                           dplyr::select(YEAR, `SCHOOL ID (R-C-D-T-S)`, 
                                         School_ID, 
                                         `SCHOOL - BLACK %`,
                                         `SCHOOL - WHITE %`,
                                        `SCHOOL - HISPANIC %`,
                                        `SCHOOL - ASIAN %`) %>%
              group_by(YEAR, `SCHOOL ID (R-C-D-T-S)`) %>% 
              gather(group_name, pct, -`SCHOOL ID (R-C-D-T-S)`, -School_ID, -YEAR) %>% 
           # sanity check to make sure all races in output to start before slicing
             # arrange(YEAR, `SCHOOL ID (R-C-D-T-S)`)  %>% 
                         slice(which.max(pct)) %>% 
                         mutate(
                           predominant_race = ifelse(
                           group_name == 'SCHOOL - BLACK %', 'Black',
                           ifelse(group_name == 'SCHOOL - WHITE %', 'White',
                           ifelse(group_name == 'SCHOOL - ASIAN %', 'Asian',
                           ifelse(group_name == 'SCHOOL - HISPANIC %', 'Latinx',
                                  'Other')
                           )))
                           ) %>%
              dplyr::select(`SCHOOL ID (R-C-D-T-S)`, YEAR, 
                            predominant_race, max_pct = pct), 
          by = c("SCHOOL ID (R-C-D-T-S)", "YEAR")) %>% 
  dplyr::select(front_cols, ENROLLMENT_RANGE, SPEND_RANGE, 
                predominant_race, max_pct, everything())
    

```




```{r fig.height=12, fig.width=15, message=FALSE, warning=FALSE}
library(ggridges)
library(cowplot)

school_data %>%        
  ggplot(aes(x = AVG_SPEND_PER_STUDENT, y = as.factor(YEAR))) +
      geom_density_ridges( mapping = aes(x = AVG_SPEND_PER_STUDENT,
                            y = as.factor(YEAR), color=predominant_race, 
                            size=3), fill=NA) +
  scale_color_dt("diverging", reverse = TRUE, na.value=get_dt_cols("palegray")) +
    scale_x_continuous(labels = scales::dollar, limits=c(0,20000)) + 
  theme_modest() + 
  labs(title = "2018 School Funding Update Increased Spread of Annual Spend per Student", fontface='bold')
```


 




```{r fig.height=12, fig.width=15, message=FALSE, warning=FALSE}
facet_sides_labels <- as_labeller(c(`Far North` = "Far North Side", 
                   `Far Southeast` = "Far Southeast Side",
                   `Far Southwast` = "Far Southwast Side",
                   North = "North Side",
                   Northwest= "Northwest Side",
                   South = "South Side",
                   Southwest = "Southwest Side",
                   West = "West Side",
                   `NA` = "Side Unavailable"))

#                                       
# 
# facet_sides_labels2 <- c("Far North" = "Far North Side", 
#                    "Far Southeast" = "Far Southeast Side",
#                    "Far Southwast" = "Far Southwast Side",
#                    "North" = "North Side",
#                    "Northwest"= "Northwest Side",
#                    "South" = "South Side",
#                    "Southwest" = "Southwest Side",
#                    "West" = "West Side",
#                    "NA" = "Side Information Not Available") 
#  
# 
# 
both_plots <- plot_grid(
school_data %>%
  ggplot(aes(x = AVG_SPEND_PER_STUDENT, y = as.factor(YEAR))) +
      geom_density_ridges( mapping = aes(x = AVG_SPEND_PER_STUDENT,
                            y = as.factor(YEAR), fill=predominant_race)) +
  scale_fill_dt(reverse = TRUE, na.value=get_dt_cols("palegray")) +
    scale_x_continuous(labels = scales::dollar, limits=c(0,20000)) +
  theme_modest(),
NULL,
  school_data %>%
ggplot(aes(x = AVG_SPEND_PER_STUDENT, y = as.factor(YEAR))) +
      geom_density_ridges(
                          mapping = aes(x = AVG_SPEND_PER_STUDENT,
                            y = as.factor(YEAR), fill=predominant_race) ) +
  scale_fill_dt("main", reverse = TRUE, na.value=get_dt_cols("palegray")) +
    scale_x_continuous(labels = scales::dollar) +
  theme_modest() +
  facet_wrap(SIDE ~ ., labeller = facet_sides_labels),
ncol = 1, rel_heights =  c(1, 0.1, 1), align = 'v')

title <- ggdraw() + draw_label("2018 School Funding Update Increased Spread of Annual Spend per Student", fontface='bold', size=50)
plot_grid(title, both_plots, ncol=1, rel_heights=c(0.1, 1))
```




```{r fig.height=12, fig.width=15}
school_data %>% 
  filter(!is.na(SPEND_RANGE)) %>%
  ggplot(aes(SPEND_RANGE)) +
  # geom_line(aes(y=AVG_SPEND_PER_STUDENT, x=YEAR)) +
  geom_bar(aes(group=as.factor(predominant_race), fill=predominant_race)) +
    scale_fill_dt(na.value=get_dt_cols("palegray")) +

  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))
        ) +
  facet_wrap(~YEAR)
```




```{r}
left_join(just_demos, as.data.frame(wards_w_all_demos) %>% distinct(WARD, GEOID), by="GEOID", na_matches="never")
```


```{r  fig.height=12, fig.width=15,  message=FALSE, warning=FALSE}
school_data <- school_data %>%
  mutate(
    SCHOOL_TOTAL_ENROLLMENT = as.numeric(gsub(",","",SCHOOL_TOTAL_ENROLLMENT)),
   YEAR = as.numeric(YEAR),
   PREV_YR = as.numeric(PREV_YR),
   TWO_YR_PRIOR = as.numeric(TWO_YR_PRIOR))


front_cols <- c("YEAR", "School_ID", "WARD", "SIDE", "SCHOOL_NAME", "NAME_WARD_JOIN", "CY_BUDGET", "SCHOOL_TOTAL_ENROLLMENT")

school_data <- school_data %>% 
  mutate(ENROLLMENT_RANGE = cut(SCHOOL_TOTAL_ENROLLMENT, breaks=c(0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, Inf), labels=c("0-499", "500-999", "1,000-1,499", "1,500-1,999", "2,000-2,499", "2,500-2,999", "3,000-3,499", "3,500-3,999", "4,000-4,499", "4,500-4,999", "5,000+"), ordered_result = TRUE),
         SPEND_RANGE = cut(AVG_SPEND_PER_STUDENT, breaks=c(0, 2500, 5000, 75000, 10000, 12500, 15000, Inf), labels=c("0-2,499", "2,500-4,999", "5,000-7,499", "7,500-9,999", "10,000-12,499", "12,500-14,999", "15,000+"), ordered_result = TRUE)) %>%
  dplyr::select(one_of(front_cols), ENROLLMENT_RANGE,SPEND_RANGE, everything())




school_data %>% group_by(YEAR, predominant_race, ENROLLMENT_RANGE) %>% summarise(median_spend = median(AVG_SPEND_PER_STUDENT)) %>%
  ggplot(aes(x=median_spend, y=ENROLLMENT_RANGE, group=as.factor(predominant_race))) +
  geom_point(aes(color=SIDE), position="jitter",size=6) +
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1))) +
  facet_wrap(~YEAR)
```



```{r fig.height=12, fig.width=15}
school_data %>% 
  group_by(YEAR, predominant_race) %>% 
  summarise(median_class_size = mean(as.integer(`OVERALL AVERAGE CLASS SIZE - SCHOOL`), na.rm=TRUE),
            num_schools = n()) %>%
  ggplot() +
  geom_line(aes(x=as.numeric(YEAR), y=median_class_size, group=as.factor(predominant_race), color=predominant_race)) +
    scale_color_dt(na.value=get_dt_cols("palegray")) +
  theme_modest() +
  theme(legend.text = element_text(size=rel(1)),
        legend.title = element_text(size=rel(1)))
```


```{r echo=TRUE}
colnames(school_data)
```

```{r match-unit-ids, message=FALSE, warning=FALSE}

id.Unit <- read_csv(here::here("data", "rc_v2", "2001_to_2014_unit_School_ID_matchup.csv"), col_names = T, skip=1) %>% distinct(`School ID`, Unit) %>% dplyr::select(School_ID = `School ID`, Unit)

files <- dir(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race"), 
                 pattern = '\\.xls', full.names = TRUE)
```



```{r}


for (i in length(files)) {
  files[i] <- sub('.*\\/', '',files[i])
  left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_20thDay_2019.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`)), 
  id.Unit, by=c(`School ID` = "School_ID") )
  
}
```
```{r}
files
```


```{r}
yoyTotalEnrollment <- bind_rows(
  left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_20thDay_2019.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2019), 
  id.Unit, by=c(`School ID` = "School_ID") ),
  left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_20thDay_2018.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2018), 
  id.Unit, by=c(`School ID` = "School_ID") ),
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_20thDay_2017.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2017), 
  left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "enrollment_20th_day_2016_GV_20151023.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`)), 
  id.Unit, by=c(`School ID` = "School_ID"),
           YEAR = 2016),
  left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "enrollment_20th_day_2014-15.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2015), 
  id.Unit, by=c(`School ID` = "School_ID") ),

left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "enrollment_20th_day_2014.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2014), 
  id.Unit, by=c(`School ID` = "School_ID") ),
left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "enrollment_20th_day_2013.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2013), 
  id.Unit, by=c(`School ID` = "School_ID") ),
read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "membership_20th_day_2012.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR=2012)
) %>% mutate(Total = ifelse(is.na(Total), Totals, Total)) %>% filter(!(is.na(`School ID`) & is.na(Unit)) & !is.na(Total))
  
```



```{r}
schoolDemosTotalEnrollment <- bind_rows(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_RacialEthnic_2019.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2019),
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_RacialEthnic_2018.xls")) %>% mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2018),
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_RacialEthnic_2017.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2017), 
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY16_Student_Racial_Ethnic_Report_20151023.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`), 
           YEAR = 2016),
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY15_Racial_Ethnic_Survey.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2015), 
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY14_Racial_Ethnic_Survey.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2014), 
  id.Unit, by=c(`School ID` = "School_ID") ),
left_join(
  read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY13_Racial_Ethnic_Survey.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR = 2013), 
  id.Unit, by=c(`School ID` = "School_ID") ),
read_xls(here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY12_Racial_Ethnic_Survey.xls")) %>%
    mutate(`School ID` = as.integer(`School ID`),
           YEAR=2012)
) %>% mutate(Total = ifelse(is.na(Total), Totals, Total)) %>% filter(!(is.na(`School ID`) & is.na(Unit)) & !is.na(Total))

```






```{r}
multiHeader <- function(filename, sheet=NA, col_names=FALSE, na="..", n_max=1) {
  headers <- read_xls(filename, sheet=sheet, col_names = col_names, na=na, n_max = n_max)
  
  # fill only works down or up, so have to transpose headers
  long_headers = data.frame(t(headers))
  # Add column names down the columns
  long_headers <- fill(long_headers,1:n_max) # all four columns
  headers <- data.frame(t(long_headers)) # back to vertical.
  
  headers <- headers %>%
  mutate_all(as.character) %>%
  fill(names(.), .direction = "up") %>% 
    mutate_all(., funs(replace(.,duplicated(.), NA))) %>% 
    mutate_all(str_replace_na)
  
 #  # summarize using str_c from stringr which collapses strings.
 #  # summarize_all makes it work on all columns.
  column_labels <- headers %>% summarize_all(str_c, collapse = " ")
  for (i in length(column_labels)) {
    column_labels[i] <- str_replace_all(column_labels[i], "\r?\n|\r|\n", "\\s")
    column_labels[i] <- str_replace_all(column_labels[i], "n/\n", "n/\\s ")
    column_labels[i] <- gsub("NA", "",column_labels[i])
  }
 # pull them into one character vector
 headers = unlist(column_labels[1,])
 headers = unname(headers)

  for (i in 1:length(headers)) {
  if (is.character(headers[[i]])) { 
    if (str_detect(headers[[i]], "(20th.*)([0-9]{4})[-]([0-9]{4} )")) {
  headers[i] <- unlist(strsplit(headers[[i]], "(20th.*)([0-9]{4})[-]([0-9]{4} )"))[2]
    } else if (str_detect(headers[[i]], " NA")) {
      headers[i] <- unlist(strsplit(headers[[i]], " NA"))[1]
    }
  }
}
 
  return(headers)
} 

```


```{r}
multiHeader(filename=here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "Demographics_RacialEthnic_2019.xls"), sheet="Schools", n_max=2)
```


```{r}
multiHeader(filename=here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY15_Racial_Ethnic_Survey.xls"), sheet="Educational Units", n_max=2)
```

```{r}
multiHeader(filename=here::here("data", "rc_v2", "Enrollment_Info_SpEd_Race", "FY16_Student_Racial_Ethnic_Report_20151023.xls"), sheet="Educational Units", n_max=2)

```


```{r message=FALSE, warning=FALSE}

id.Unit <- read_csv(here::here("data", "rc_v2", "2001_to_2014_unit_School_ID_matchup.csv"), col_names = T, skip=1) %>% distinct(`School ID`, Unit) %>% dplyr::select(School_ID = `School ID`, Unit)

all_budgets <-  readRDS(here::here("data", "all_budgets.Rda"))
id_overlap <-  readRDS(here::here("data", "id_overlap.Rda"))
school_data <-  readRDS(here::here("data", "combined_school_data.Rda"))
                                   
dim(school_data %>% filter(is.na(School_ID)))
                                   
dim(school_data %>% filter(!is.na(School_ID) & !is.na(`SCHOOL ID (R-C-D-T-S)`)))

school_data %>% filter(!is.na(School_ID) & !is.na(`SCHOOL ID (R-C-D-T-S)`) &
  !is.na(``))

# Schools per year 325-399 every year
school_data %>% filter(!is.na(School_ID) & !is.na(`SCHOOL ID (R-C-D-T-S)`)) %>% 
  filter(!is.na(`Proposed Budget`)) %>% 
  dplyr::select(contains("budget"), School_ID, `SCHOOL ID (R-C-D-T-S)`, `SCHOOL NAME`, everything()) %>% 
  group_by(YEAR, `SCHOOL ID (R-C-D-T-S)`) %>% group_by(YEAR) %>% summarise(schools = n())
                 
write_csv(all_budgets, "all_budgets.csv")
                                                     
inner_join(id_overlap %>% 
             mutate(Legacy_Unit_ID = as.numeric(Legacy_Unit_ID)),
           id.Unit %>% 
             mutate(Unit = as.numeric(Unit)), 
           by=c(Legacy_Unit_ID="Unit")) %>% dplyr::select(School_ID, Finance_ID, YEAR)
```

```{r}

```


